from datetime import date,datetime
from decimal import Decimal
from uuid import UUID,uuid4
from sqlalchemy import Boolean,CheckConstraint,Date,DateTime,ForeignKey,Index,Integer,JSON,Numeric,String,Text,UniqueConstraint,Uuid,func,text
from sqlalchemy.orm import Mapped,mapped_column,relationship
from sqlalchemy.dialects.postgresql import JSONB
from app.db.base import Base
class Tech:
    created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),nullable=False)
    updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),onupdate=func.now(),nullable=False)
class DataSource(Tech,Base):
    __tablename__='data_sources';__table_args__=(CheckConstraint("dataset_type IN ('CNE_ELECTORAL_RESULTS','CNE_CANDIDATES','CNE_POLITICAL_ORGANIZATIONS','CNE_TURNOUT','CNE_ELECTORAL_ROLL_SNAPSHOT','INEC_DEMOGRAPHIC_INDICATORS','INEC_POPULATION_PROJECTIONS','INEC_GEOGRAPHIC_CLASSIFIER','OTHER_AGGREGATED_OFFICIAL','CNE_POLLING_PLACES','CNE_ELECTORAL_BOARDS')",name='dataset_type'),Index('ix_data_sources_code','code',unique=True))
    id:Mapped[UUID]=mapped_column(Uuid(as_uuid=True),primary_key=True,default=uuid4);code:Mapped[str]=mapped_column(String(100),nullable=False);institution:Mapped[str]=mapped_column(String(180),nullable=False);dataset_name:Mapped[str]=mapped_column(String(250),nullable=False);dataset_type:Mapped[str]=mapped_column(String(50),nullable=False);official_url:Mapped[str|None]=mapped_column(String(1000));publication_date:Mapped[date|None]=mapped_column(Date);reference_date:Mapped[date|None]=mapped_column(Date);reference_year:Mapped[int|None]=mapped_column(Integer);license_or_terms:Mapped[str|None]=mapped_column(Text);description:Mapped[str|None]=mapped_column(Text);is_official:Mapped[bool]=mapped_column(Boolean,default=True,server_default='true',nullable=False);is_active:Mapped[bool]=mapped_column(Boolean,default=True,server_default='true',nullable=False);created_by_user_id:Mapped[UUID]=mapped_column(ForeignKey('users.id',ondelete='RESTRICT'),nullable=False)
class DataImportJob(Base):
    __tablename__='data_import_jobs';__table_args__=(CheckConstraint("status IN ('RECEIVED','VALIDATING','VALIDATED','IMPORTING','COMPLETED','FAILED','REJECTED')",name='status'),CheckConstraint('file_size_bytes >= 0 AND rows_read >= 0 AND rows_valid >= 0 AND rows_inserted >= 0 AND rows_updated >= 0 AND rows_skipped >= 0 AND rows_failed >= 0',name='nonnegative_counts'),Index('ix_data_import_jobs_source_id','source_id'),Index('ix_data_import_jobs_dataset_type','dataset_type'),Index('ix_data_import_jobs_status','status'),Index('ix_data_import_jobs_file_sha256','file_sha256'),Index('ix_data_import_jobs_source_type_sha','source_id','dataset_type','file_sha256'))
    id:Mapped[UUID]=mapped_column(Uuid(as_uuid=True),primary_key=True,default=uuid4);source_id:Mapped[UUID]=mapped_column(ForeignKey('data_sources.id',ondelete='RESTRICT'),nullable=False);dataset_type:Mapped[str]=mapped_column(String(50),nullable=False);original_filename:Mapped[str]=mapped_column(String(255),nullable=False);file_sha256:Mapped[str]=mapped_column(String(64),nullable=False);file_size_bytes:Mapped[int]=mapped_column(Integer,nullable=False);status:Mapped[str]=mapped_column(String(20),nullable=False);validation_only:Mapped[bool]=mapped_column(Boolean,default=False,nullable=False);rows_read:Mapped[int]=mapped_column(Integer,default=0,nullable=False);rows_valid:Mapped[int]=mapped_column(Integer,default=0,nullable=False);rows_inserted:Mapped[int]=mapped_column(Integer,default=0,nullable=False);rows_updated:Mapped[int]=mapped_column(Integer,default=0,nullable=False);rows_skipped:Mapped[int]=mapped_column(Integer,default=0,nullable=False);rows_failed:Mapped[int]=mapped_column(Integer,default=0,nullable=False);encoding_used:Mapped[str|None]=mapped_column(String(30));delimiter_used:Mapped[str|None]=mapped_column(String(5));mapping_profile:Mapped[str|None]=mapped_column(String(100));error_summary:Mapped[str|None]=mapped_column(Text);executed_by_user_id:Mapped[UUID]=mapped_column(ForeignKey('users.id',ondelete='RESTRICT'),nullable=False);started_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),nullable=False);finished_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),nullable=False)
class DataImportError(Base):
    __tablename__='data_import_errors';__table_args__=(Index('ix_data_import_errors_import_job_id','import_job_id'),)
    id:Mapped[UUID]=mapped_column(Uuid(as_uuid=True),primary_key=True,default=uuid4);import_job_id:Mapped[UUID]=mapped_column(ForeignKey('data_import_jobs.id',ondelete='CASCADE'),nullable=False);row_number:Mapped[int|None]=mapped_column(Integer);column_name:Mapped[str|None]=mapped_column(String(100));error_code:Mapped[str]=mapped_column(String(80),nullable=False);message:Mapped[str]=mapped_column(String(500),nullable=False);rejected_value_preview:Mapped[str|None]=mapped_column(String(120));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),nullable=False)
class DatasetVersion(Tech,Base):
    __tablename__='dataset_versions';__table_args__=(CheckConstraint("status IN ('DRAFT','VALIDATED','ACTIVE','SUPERSEDED','REJECTED','ARCHIVED')",name='status'),Index('ix_dataset_versions_source_id','data_source_id'),Index('ix_dataset_versions_dataset_type','dataset_type'),Index('ix_dataset_versions_import_job_id','import_job_id',unique=True),Index('ix_dataset_versions_active_scope','data_source_id','dataset_type',unique=True,postgresql_where=text("status = 'ACTIVE'"),sqlite_where=text("status = 'ACTIVE'")))
    id:Mapped[UUID]=mapped_column(Uuid(as_uuid=True),primary_key=True,default=uuid4);data_source_id:Mapped[UUID]=mapped_column(ForeignKey('data_sources.id',ondelete='RESTRICT'),nullable=False);dataset_type:Mapped[str]=mapped_column(String(50),nullable=False);reference_date:Mapped[date|None]=mapped_column(Date);version_label:Mapped[str]=mapped_column(String(150),nullable=False);checksum:Mapped[str]=mapped_column(String(64),nullable=False);import_job_id:Mapped[UUID]=mapped_column(ForeignKey('data_import_jobs.id',ondelete='RESTRICT'),nullable=False);status:Mapped[str]=mapped_column(String(20),nullable=False,default='VALIDATED');activated_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));activated_by_user_id:Mapped[UUID|None]=mapped_column(ForeignKey('users.id',ondelete='RESTRICT'));superseded_by_id:Mapped[UUID|None]=mapped_column(ForeignKey('dataset_versions.id'))
class ElectoralProcess(Tech,Base):
    __tablename__='electoral_processes';__table_args__=(CheckConstraint("process_type IN ('SECTIONAL','GENERAL','REFERENDUM','CONSULTATION','OTHER')",name='process_type'),CheckConstraint("status IN ('DRAFT','IMPORTED','VALIDATED','PUBLISHED','ARCHIVED')",name='status'),CheckConstraint('year = EXTRACT(YEAR FROM election_date)',name='year_matches_date').ddl_if(dialect='postgresql'),Index('ix_electoral_processes_code','code',unique=True),Index('ix_electoral_processes_year','year'),Index('ix_electoral_processes_type','process_type'),Index('ix_electoral_processes_status','status'))
    id:Mapped[UUID]=mapped_column(Uuid(as_uuid=True),primary_key=True,default=uuid4);code:Mapped[str]=mapped_column(String(100),nullable=False);name:Mapped[str]=mapped_column(String(250),nullable=False);process_type:Mapped[str]=mapped_column(String(20),nullable=False);election_date:Mapped[date]=mapped_column(Date,nullable=False);year:Mapped[int]=mapped_column(Integer,nullable=False);status:Mapped[str]=mapped_column(String(20),nullable=False);is_final:Mapped[bool]=mapped_column(Boolean,default=True,nullable=False);source_id:Mapped[UUID]=mapped_column(ForeignKey('data_sources.id',ondelete='RESTRICT'),nullable=False);description:Mapped[str|None]=mapped_column(Text);is_active:Mapped[bool]=mapped_column(Boolean,default=True,nullable=False)
class ElectoralMilestone(Tech,Base):
    __tablename__='electoral_milestones';__table_args__=(CheckConstraint("milestone_type IN ('CONVOCATORIA','CANDIDATE_REGISTRATION','CAMPAIGN_PERIOD','DEBATE','ELECTORAL_SILENCE','ELECTION_DAY','VOTE_COUNT','OTHER')",name='milestone_type'),CheckConstraint("status IN ('ACTIVE','ARCHIVED')",name='status'),Index('ix_electoral_milestones_process_id','electoral_process_id'),Index('ix_electoral_milestones_starts_at','starts_at'),Index('ix_electoral_milestones_status','status'),Index('uq_electoral_milestones_identity','electoral_process_id','milestone_type','starts_at','title',unique=True))
    id:Mapped[UUID]=mapped_column(Uuid(as_uuid=True),primary_key=True,default=uuid4);electoral_process_id:Mapped[UUID]=mapped_column(ForeignKey('electoral_processes.id',ondelete='RESTRICT'),nullable=False);title:Mapped[str]=mapped_column(String(250),nullable=False);description:Mapped[str|None]=mapped_column(Text);milestone_type:Mapped[str]=mapped_column(String(30),nullable=False);starts_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);ends_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));source_id:Mapped[UUID]=mapped_column(ForeignKey('data_sources.id',ondelete='RESTRICT'),nullable=False);source_url:Mapped[str|None]=mapped_column(String(1000));import_job_id:Mapped[UUID|None]=mapped_column(ForeignKey('data_import_jobs.id',ondelete='RESTRICT'));dataset_version_id:Mapped[UUID|None]=mapped_column(ForeignKey('dataset_versions.id',ondelete='RESTRICT'));is_official:Mapped[bool]=mapped_column(Boolean,default=True,server_default='true',nullable=False);status:Mapped[str]=mapped_column(String(20),nullable=False,default='ACTIVE');created_by_user_id:Mapped[UUID]=mapped_column(ForeignKey('users.id',ondelete='RESTRICT'),nullable=False)
class ElectoralContest(Tech,Base):
    __tablename__='electoral_contests';__table_args__=(CheckConstraint("office_type IN ('MAYOR','URBAN_COUNCILOR','RURAL_COUNCILOR','PARISH_BOARD','PREFECTURE','OTHER')",name='office_type'),CheckConstraint("vote_method IN ('SINGLE_CHOICE','MULTI_VOTE','LIST_VOTE','OTHER')",name='vote_method'),CheckConstraint('seats >= 1',name='seats'),CheckConstraint("office_type != 'MAYOR' OR canton_id IS NOT NULL",name='mayor_canton'),CheckConstraint("office_type != 'PARISH_BOARD' OR parish_id IS NOT NULL",name='parish_board_parish'),UniqueConstraint('electoral_process_id','office_type','province_id','canton_id','parish_id','name',name='uq_electoral_contests_equivalent'),Index('ix_electoral_contests_process_id','electoral_process_id'))
    id:Mapped[UUID]=mapped_column(Uuid(as_uuid=True),primary_key=True,default=uuid4);electoral_process_id:Mapped[UUID]=mapped_column(ForeignKey('electoral_processes.id',ondelete='RESTRICT'),nullable=False);office_type:Mapped[str]=mapped_column(String(30),nullable=False);name:Mapped[str]=mapped_column(String(250),nullable=False);vote_method:Mapped[str]=mapped_column(String(20),nullable=False);province_id:Mapped[int|None]=mapped_column(ForeignKey('provinces.id'));canton_id:Mapped[int|None]=mapped_column(ForeignKey('cantons.id'));parish_id:Mapped[int|None]=mapped_column(ForeignKey('parishes.id'));seats:Mapped[int]=mapped_column(Integer,default=1,nullable=False);is_active:Mapped[bool]=mapped_column(Boolean,default=True,nullable=False)
class PoliticalOrganization(Tech,Base):
    __tablename__='political_organizations';__table_args__=(UniqueConstraint('source_id','external_code',name='uq_political_organizations_source_code'),)
    id:Mapped[UUID]=mapped_column(Uuid(as_uuid=True),primary_key=True,default=uuid4);external_code:Mapped[str|None]=mapped_column(String(100));name:Mapped[str]=mapped_column(String(250),nullable=False);short_name:Mapped[str|None]=mapped_column(String(100));organization_type:Mapped[str|None]=mapped_column(String(100));list_number:Mapped[str|None]=mapped_column(String(30));scope:Mapped[str|None]=mapped_column(String(100));source_id:Mapped[UUID]=mapped_column(ForeignKey('data_sources.id',ondelete='RESTRICT'),nullable=False);is_active:Mapped[bool]=mapped_column(Boolean,default=True,nullable=False)
class ElectoralGeography(Tech,Base):
    __tablename__='electoral_geographies';__table_args__=(CheckConstraint("level IN ('PROVINCE','CANTON','PARISH','ZONE','PRECINCT','JRV')",name='level'),UniqueConstraint('electoral_process_id','level','external_code',name='uq_electoral_geographies_process_level_code'),Index('ix_electoral_geographies_process_id','electoral_process_id'),Index('ix_electoral_geographies_level','level'),Index('ix_electoral_geographies_external_code','external_code'),Index('ix_electoral_geographies_canton_id','canton_id'),Index('ix_electoral_geographies_parish_id','parish_id'))
    id:Mapped[UUID]=mapped_column(Uuid(as_uuid=True),primary_key=True,default=uuid4);electoral_process_id:Mapped[UUID]=mapped_column(ForeignKey('electoral_processes.id',ondelete='RESTRICT'),nullable=False);level:Mapped[str]=mapped_column(String(20),nullable=False);external_code:Mapped[str]=mapped_column(String(100),nullable=False);name:Mapped[str]=mapped_column(String(250),nullable=False);parent_id:Mapped[UUID|None]=mapped_column(ForeignKey('electoral_geographies.id'));province_id:Mapped[int|None]=mapped_column(ForeignKey('provinces.id'));canton_id:Mapped[int|None]=mapped_column(ForeignKey('cantons.id'));parish_id:Mapped[int|None]=mapped_column(ForeignKey('parishes.id'));zone_code:Mapped[str|None]=mapped_column(String(50));precinct_code:Mapped[str|None]=mapped_column(String(50));jrv_code:Mapped[str|None]=mapped_column(String(50));is_mapped:Mapped[bool]=mapped_column(Boolean,default=False,nullable=False);is_active:Mapped[bool]=mapped_column(Boolean,default=True,nullable=False)
class ElectoralCandidate(Tech,Base):
    __tablename__='electoral_candidates';__table_args__=(UniqueConstraint('electoral_contest_id','external_code',name='uq_electoral_candidates_contest_code'),)
    id:Mapped[UUID]=mapped_column(Uuid(as_uuid=True),primary_key=True,default=uuid4);electoral_contest_id:Mapped[UUID]=mapped_column(ForeignKey('electoral_contests.id',ondelete='RESTRICT'),nullable=False);political_organization_id:Mapped[UUID|None]=mapped_column(ForeignKey('political_organizations.id'));external_code:Mapped[str]=mapped_column(String(100),nullable=False);full_name:Mapped[str]=mapped_column(String(250),nullable=False);display_name:Mapped[str|None]=mapped_column(String(250));list_number:Mapped[str|None]=mapped_column(String(30));ballot_order:Mapped[int|None]=mapped_column(Integer);is_winner:Mapped[bool]=mapped_column(Boolean,default=False,nullable=False);source_id:Mapped[UUID]=mapped_column(ForeignKey('data_sources.id',ondelete='RESTRICT'),nullable=False);is_active:Mapped[bool]=mapped_column(Boolean,default=True,nullable=False)
class ElectoralTurnout(Tech,Base):
    __tablename__='electoral_turnout';__table_args__=(CheckConstraint('registered_voters>=0 AND ballots_cast>=0 AND valid_votes>=0 AND blank_votes>=0 AND null_votes>=0 AND other_votes>=0',name='nonnegative'),CheckConstraint('ballots_cast <= registered_voters',name='cast_lte_registered'),UniqueConstraint('electoral_contest_id','electoral_geography_id',name='uq_electoral_turnout_contest_geography'),Index('ix_electoral_turnout_contest_id','electoral_contest_id'),Index('ix_electoral_turnout_geography_id','electoral_geography_id'),Index('ix_electoral_turnout_contest_geography','electoral_contest_id','electoral_geography_id'))
    id:Mapped[UUID]=mapped_column(Uuid(as_uuid=True),primary_key=True,default=uuid4);electoral_contest_id:Mapped[UUID]=mapped_column(ForeignKey('electoral_contests.id',ondelete='RESTRICT'),nullable=False);electoral_geography_id:Mapped[UUID]=mapped_column(ForeignKey('electoral_geographies.id',ondelete='RESTRICT'),nullable=False);registered_voters:Mapped[int]=mapped_column(Integer,nullable=False);ballots_cast:Mapped[int]=mapped_column(Integer,nullable=False);valid_votes:Mapped[int]=mapped_column(Integer,nullable=False);blank_votes:Mapped[int]=mapped_column(Integer,nullable=False);null_votes:Mapped[int]=mapped_column(Integer,nullable=False);other_votes:Mapped[int]=mapped_column(Integer,default=0,nullable=False);is_final:Mapped[bool]=mapped_column(Boolean,default=True,nullable=False);source_id:Mapped[UUID]=mapped_column(ForeignKey('data_sources.id',ondelete='RESTRICT'),nullable=False);import_job_id:Mapped[UUID]=mapped_column(ForeignKey('data_import_jobs.id',ondelete='RESTRICT'),nullable=False);is_active:Mapped[bool]=mapped_column(Boolean,default=True,nullable=False)
class ElectoralCandidateResult(Tech,Base):
    __tablename__='electoral_candidate_results';__table_args__=(CheckConstraint('votes >= 0',name='votes_nonnegative'),UniqueConstraint('electoral_contest_id','electoral_geography_id','electoral_candidate_id',name='uq_candidate_results_contest_geography_candidate'),Index('ix_candidate_results_contest_id','electoral_contest_id'),Index('ix_candidate_results_geography_id','electoral_geography_id'),Index('ix_candidate_results_candidate_id','electoral_candidate_id'))
    id:Mapped[UUID]=mapped_column(Uuid(as_uuid=True),primary_key=True,default=uuid4);electoral_contest_id:Mapped[UUID]=mapped_column(ForeignKey('electoral_contests.id',ondelete='RESTRICT'),nullable=False);electoral_geography_id:Mapped[UUID]=mapped_column(ForeignKey('electoral_geographies.id',ondelete='RESTRICT'),nullable=False);electoral_candidate_id:Mapped[UUID]=mapped_column(ForeignKey('electoral_candidates.id',ondelete='RESTRICT'),nullable=False);votes:Mapped[int]=mapped_column(Integer,nullable=False);is_final:Mapped[bool]=mapped_column(Boolean,default=True,nullable=False);source_id:Mapped[UUID]=mapped_column(ForeignKey('data_sources.id',ondelete='RESTRICT'),nullable=False);import_job_id:Mapped[UUID]=mapped_column(ForeignKey('data_import_jobs.id',ondelete='RESTRICT'),nullable=False);is_active:Mapped[bool]=mapped_column(Boolean,default=True,nullable=False)
class DemographicIndicator(Tech,Base):
    __tablename__='demographic_indicators';__table_args__=(CheckConstraint("category IN ('POPULATION','AGE','EDUCATION','EMPLOYMENT','HOUSING','WATER','SEWERAGE','INTERNET','MIGRATION','TRANSPORT','OTHER')",name='category'),CheckConstraint("unit IN ('COUNT','PERCENT','RATE','INDEX','YEARS','OTHER')",name='unit'),CheckConstraint("value_type IN ('INTEGER','DECIMAL')",name='value_type'),Index('ix_demographic_indicators_code','code',unique=True))
    id:Mapped[UUID]=mapped_column(Uuid(as_uuid=True),primary_key=True,default=uuid4);code:Mapped[str]=mapped_column(String(100),nullable=False);name:Mapped[str]=mapped_column(String(250),nullable=False);description:Mapped[str|None]=mapped_column(Text);category:Mapped[str]=mapped_column(String(30),nullable=False);unit:Mapped[str]=mapped_column(String(20),nullable=False);value_type:Mapped[str]=mapped_column(String(20),nullable=False);source_id:Mapped[UUID]=mapped_column(ForeignKey('data_sources.id',ondelete='RESTRICT'),nullable=False);is_active:Mapped[bool]=mapped_column(Boolean,default=True,nullable=False)
class DemographicObservation(Tech,Base):
    __tablename__='demographic_observations';__table_args__=(CheckConstraint("geography_level IN ('PROVINCE','CANTON','PARISH')",name='level'),CheckConstraint('reference_year BETWEEN 1900 AND 2200',name='year'),CheckConstraint('denominator IS NULL OR denominator > 0',name='denominator_positive'),UniqueConstraint('demographic_indicator_id','geography_level','province_id','canton_id','parish_id','reference_year','source_id',name='uq_demographic_observations_key'),Index('ix_demographic_observations_indicator_id','demographic_indicator_id'),Index('ix_demographic_observations_year','reference_year'),Index('ix_demographic_observations_canton_id','canton_id'),Index('ix_demographic_observations_parish_id','parish_id'),Index('ix_demographic_observations_source_id','source_id'))
    id:Mapped[UUID]=mapped_column(Uuid(as_uuid=True),primary_key=True,default=uuid4);demographic_indicator_id:Mapped[UUID]=mapped_column(ForeignKey('demographic_indicators.id',ondelete='RESTRICT'),nullable=False);geography_level:Mapped[str]=mapped_column(String(20),nullable=False);province_id:Mapped[int|None]=mapped_column(ForeignKey('provinces.id'));canton_id:Mapped[int|None]=mapped_column(ForeignKey('cantons.id'));parish_id:Mapped[int|None]=mapped_column(ForeignKey('parishes.id'));reference_year:Mapped[int]=mapped_column(Integer,nullable=False);value:Mapped[Decimal]=mapped_column(Numeric(20,4),nullable=False);numerator:Mapped[Decimal|None]=mapped_column(Numeric(20,4));denominator:Mapped[Decimal|None]=mapped_column(Numeric(20,4));source_id:Mapped[UUID]=mapped_column(ForeignKey('data_sources.id',ondelete='RESTRICT'),nullable=False);import_job_id:Mapped[UUID]=mapped_column(ForeignKey('data_import_jobs.id',ondelete='RESTRICT'),nullable=False);is_official:Mapped[bool]=mapped_column(Boolean,default=True,nullable=False);is_active:Mapped[bool]=mapped_column(Boolean,default=True,nullable=False)

class ElectoralRollSnapshot(Tech,Base):
    __tablename__='electoral_roll_snapshots';__table_args__=(CheckConstraint("status IN ('DRAFT','IMPORTED','VALIDATED','PUBLISHED','ARCHIVED')",name='status'),Index('ix_roll_snapshots_source_id','source_id'),Index('ix_roll_snapshots_date','snapshot_date'))
    id:Mapped[UUID]=mapped_column(Uuid(as_uuid=True),primary_key=True,default=uuid4);source_id:Mapped[UUID]=mapped_column(ForeignKey('data_sources.id',ondelete='RESTRICT'),nullable=False);electoral_process_id:Mapped[UUID|None]=mapped_column(ForeignKey('electoral_processes.id',ondelete='RESTRICT'));snapshot_date:Mapped[date]=mapped_column(Date,nullable=False);name:Mapped[str]=mapped_column(String(250),nullable=False);status:Mapped[str]=mapped_column(String(20),nullable=False,default='IMPORTED');is_final:Mapped[bool]=mapped_column(Boolean,default=True,nullable=False);notes:Mapped[str|None]=mapped_column(Text);created_by_user_id:Mapped[UUID]=mapped_column(ForeignKey('users.id',ondelete='RESTRICT'),nullable=False)

class ElectoralRollSnapshotEntry(Tech,Base):
    __tablename__='electoral_roll_snapshot_entries';__table_args__=(CheckConstraint("geography_level IN ('PROVINCE','CANTON','PARISH')",name='level'),CheckConstraint('registered_voters >= 0 AND (male_voters IS NULL OR male_voters >= 0) AND (female_voters IS NULL OR female_voters >= 0) AND (electoral_zones IS NULL OR electoral_zones >= 0) AND (juntas IS NULL OR juntas >= 0)',name='nonnegative'),CheckConstraint('male_voters IS NULL OR female_voters IS NULL OR male_voters + female_voters = registered_voters',name='sexes_sum'),UniqueConstraint('snapshot_id','geography_level','province_id','canton_id','parish_id',name='uq_roll_snapshot_geo'))
    id:Mapped[UUID]=mapped_column(Uuid(as_uuid=True),primary_key=True,default=uuid4);snapshot_id:Mapped[UUID]=mapped_column(ForeignKey('electoral_roll_snapshots.id',ondelete='CASCADE'),nullable=False);geography_level:Mapped[str]=mapped_column(String(20),nullable=False);province_id:Mapped[int|None]=mapped_column(ForeignKey('provinces.id'));canton_id:Mapped[int|None]=mapped_column(ForeignKey('cantons.id'));parish_id:Mapped[int|None]=mapped_column(ForeignKey('parishes.id'));province_dpa:Mapped[str|None]=mapped_column(String(2));canton_dpa:Mapped[str|None]=mapped_column(String(4));parish_dpa:Mapped[str|None]=mapped_column(String(6));registered_voters:Mapped[int]=mapped_column(Integer,nullable=False);male_voters:Mapped[int|None]=mapped_column(Integer);female_voters:Mapped[int|None]=mapped_column(Integer);electoral_zones:Mapped[int|None]=mapped_column(Integer);juntas:Mapped[int|None]=mapped_column(Integer)

class ParticipationProjectionRun(Tech,Base):
    __tablename__='participation_projection_runs';__table_args__=(Index('ix_projection_runs_campaign_id','campaign_id'),Index('ix_projection_runs_snapshot_id','snapshot_id'))
    id:Mapped[UUID]=mapped_column(Uuid(as_uuid=True),primary_key=True,default=uuid4);campaign_id:Mapped[UUID|None]=mapped_column(ForeignKey('campaigns.id',ondelete='RESTRICT'));electoral_process_id:Mapped[UUID]=mapped_column(ForeignKey('electoral_processes.id',ondelete='RESTRICT'),nullable=False);snapshot_id:Mapped[UUID]=mapped_column(ForeignKey('electoral_roll_snapshots.id',ondelete='RESTRICT'),nullable=False);model_code:Mapped[str]=mapped_column(String(100),nullable=False);model_version:Mapped[str]=mapped_column(String(30),nullable=False);historical_process_ids:Mapped[list]=mapped_column(JSON().with_variant(JSONB, 'postgresql'),nullable=False);parameters:Mapped[dict]=mapped_column(JSON().with_variant(JSONB, 'postgresql'),nullable=False);run_date:Mapped[date]=mapped_column(Date,nullable=False);created_by_user_id:Mapped[UUID]=mapped_column(ForeignKey('users.id',ondelete='RESTRICT'),nullable=False)

class ParticipationProjectionResult(Tech,Base):
    __tablename__='participation_projection_results';__table_args__=(CheckConstraint('registered_voters >= 0 AND expected_voters_low >= 0 AND expected_voters_central >= 0 AND expected_voters_high >= 0',name='nonnegative'),CheckConstraint('expected_voters_low <= registered_voters AND expected_voters_central <= registered_voters AND expected_voters_high <= registered_voters',name='bounded'),UniqueConstraint('run_id','parish_id',name='uq_projection_run_parish'))
    id:Mapped[UUID]=mapped_column(Uuid(as_uuid=True),primary_key=True,default=uuid4);run_id:Mapped[UUID]=mapped_column(ForeignKey('participation_projection_runs.id',ondelete='CASCADE'),nullable=False);parish_id:Mapped[int]=mapped_column(ForeignKey('parishes.id',ondelete='RESTRICT'),nullable=False);registered_voters:Mapped[int]=mapped_column(Integer,nullable=False);turnout_rate_low:Mapped[Decimal]=mapped_column(Numeric(12,8),nullable=False);turnout_rate_central:Mapped[Decimal]=mapped_column(Numeric(12,8),nullable=False);turnout_rate_high:Mapped[Decimal]=mapped_column(Numeric(12,8),nullable=False);expected_voters_low:Mapped[int]=mapped_column(Integer,nullable=False);expected_voters_central:Mapped[int]=mapped_column(Integer,nullable=False);expected_voters_high:Mapped[int]=mapped_column(Integer,nullable=False);data_quality_status:Mapped[str]=mapped_column(String(30),nullable=False);explanation:Mapped[str]=mapped_column(Text,nullable=False)
