from datetime import date,datetime
from uuid import UUID,uuid4
from sqlalchemy import Boolean,CheckConstraint,Date,DateTime,Float,ForeignKey,Index,Integer,String,Text,UniqueConstraint,Uuid,func
from sqlalchemy.orm import Mapped,mapped_column
from app.db.base import Base
from app.db.spatial import SpatialGeometry
class CatalogFields:
    is_active:Mapped[bool]=mapped_column(Boolean,default=True,server_default="true",nullable=False)
    display_order:Mapped[int]=mapped_column(Integer,default=0,server_default="0",nullable=False)
    created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),nullable=False)
    updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),onupdate=func.now(),nullable=False)
class ActivityType(CatalogFields,Base):
    __tablename__="activity_types";__table_args__=(Index("ix_activity_types_code","code",unique=True),Index("ix_activity_types_name","name",unique=True))
    id:Mapped[int]=mapped_column(primary_key=True);code:Mapped[str]=mapped_column(String(50),nullable=False);name:Mapped[str]=mapped_column(String(120),nullable=False);description:Mapped[str|None]=mapped_column(String(255))
class NeedCategory(CatalogFields,Base):
    __tablename__="need_categories";__table_args__=(Index("ix_need_categories_code","code",unique=True),Index("ix_need_categories_name","name",unique=True))
    id:Mapped[int]=mapped_column(primary_key=True);code:Mapped[str]=mapped_column(String(50),nullable=False);name:Mapped[str]=mapped_column(String(120),nullable=False);description:Mapped[str|None]=mapped_column(String(255))
class TerritorialActivity(Base):
    __tablename__="territorial_activities";__table_args__=(CheckConstraint("status IN ('PLANNED','COMPLETED','CANCELLED')",name="status"),CheckConstraint("latitude IS NULL OR latitude BETWEEN -90 AND 90",name="latitude_range"),CheckConstraint("longitude IS NULL OR longitude BETWEEN -180 AND 180",name="longitude_range"),CheckConstraint("sector_id IS NULL OR community_id IS NOT NULL",name="sector_requires_community"),Index("ix_territorial_activities_campaign_id","campaign_id"),Index("ix_territorial_activities_activity_date","activity_date"),Index("ix_territorial_activities_status","status"),Index("ix_territorial_activities_parish_id","parish_id"),Index("ix_territorial_activities_community_id","community_id"),Index("ix_territorial_activities_sector_id","sector_id"),Index("ix_territorial_activities_responsible_user_id","responsible_user_id"),Index("ix_territorial_activities_campaign_date","campaign_id","activity_date"),Index("ix_territorial_activities_campaign_parish","campaign_id","parish_id"),Index("ix_territorial_activities_location_gist","location",postgresql_using="gist"))
    id:Mapped[UUID]=mapped_column(Uuid(as_uuid=True),primary_key=True,default=uuid4);campaign_id:Mapped[UUID]=mapped_column(ForeignKey("campaigns.id",ondelete="RESTRICT"),nullable=False);activity_type_id:Mapped[int]=mapped_column(ForeignKey("activity_types.id",ondelete="RESTRICT"),nullable=False);title:Mapped[str]=mapped_column(String(180),nullable=False);description:Mapped[str|None]=mapped_column(Text);activity_date:Mapped[date]=mapped_column(Date,nullable=False);status:Mapped[str]=mapped_column(String(20),nullable=False);parish_id:Mapped[int]=mapped_column(ForeignKey("parishes.id",ondelete="RESTRICT"),nullable=False);community_id:Mapped[UUID|None]=mapped_column(ForeignKey("communities.id",ondelete="RESTRICT"));sector_id:Mapped[UUID|None]=mapped_column(ForeignKey("sectors.id",ondelete="RESTRICT"));location_name:Mapped[str|None]=mapped_column(String(180));latitude:Mapped[float|None]=mapped_column(Float);longitude:Mapped[float|None]=mapped_column(Float);location:Mapped[str|None]=mapped_column(SpatialGeometry("POINT"));responsible_user_id:Mapped[UUID|None]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"));created_by_user_id:Mapped[UUID]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"),nullable=False);is_active:Mapped[bool]=mapped_column(Boolean,default=True,server_default="true",nullable=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),nullable=False);updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),onupdate=func.now(),nullable=False)
class ActivityParticipantSummary(Base):
    __tablename__="activity_participant_summaries";__table_args__=(Index("ix_participant_summaries_activity_id","activity_id",unique=True),CheckConstraint("estimated_attendees>=0 AND organizations_count>=0 AND community_leaders_count>=0 AND campaign_team_count>=0",name="nonnegative_counts"))
    id:Mapped[UUID]=mapped_column(Uuid(as_uuid=True),primary_key=True,default=uuid4);activity_id:Mapped[UUID]=mapped_column(ForeignKey("territorial_activities.id",ondelete="RESTRICT"),nullable=False);estimated_attendees:Mapped[int]=mapped_column(Integer,default=0,server_default="0",nullable=False);organizations_count:Mapped[int]=mapped_column(Integer,default=0,server_default="0",nullable=False);community_leaders_count:Mapped[int]=mapped_column(Integer,default=0,server_default="0",nullable=False);campaign_team_count:Mapped[int]=mapped_column(Integer,default=0,server_default="0",nullable=False);notes:Mapped[str|None]=mapped_column(Text);created_by_user_id:Mapped[UUID]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"),nullable=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),nullable=False);updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),onupdate=func.now(),nullable=False)
class CitizenNeed(Base):
    __tablename__="citizen_needs";__table_args__=(CheckConstraint("mentions_count>=1",name="mentions_positive"),CheckConstraint("priority IN ('LOW','MEDIUM','HIGH','CRITICAL')",name="priority"),CheckConstraint("status IN ('IDENTIFIED','UNDER_REVIEW','INCLUDED_IN_PLAN','DISCARDED')",name="status"),UniqueConstraint("activity_id","need_category_id","title",name="uq_citizen_needs_activity_category_title"),Index("ix_citizen_needs_campaign_id","campaign_id"),Index("ix_citizen_needs_activity_id","activity_id"),Index("ix_citizen_needs_need_category_id","need_category_id"),Index("ix_citizen_needs_priority","priority"),Index("ix_citizen_needs_status","status"),Index("ix_citizen_needs_parish_id","parish_id"),Index("ix_citizen_needs_campaign_category","campaign_id","need_category_id"),Index("ix_citizen_needs_campaign_parish","campaign_id","parish_id"))
    id:Mapped[UUID]=mapped_column(Uuid(as_uuid=True),primary_key=True,default=uuid4);campaign_id:Mapped[UUID]=mapped_column(ForeignKey("campaigns.id",ondelete="RESTRICT"),nullable=False);activity_id:Mapped[UUID]=mapped_column(ForeignKey("territorial_activities.id",ondelete="RESTRICT"),nullable=False);need_category_id:Mapped[int]=mapped_column(ForeignKey("need_categories.id",ondelete="RESTRICT"),nullable=False);title:Mapped[str]=mapped_column(String(180),nullable=False);description:Mapped[str|None]=mapped_column(Text);mentions_count:Mapped[int]=mapped_column(Integer,default=1,server_default="1",nullable=False);priority:Mapped[str]=mapped_column(String(20),nullable=False);status:Mapped[str]=mapped_column(String(30),nullable=False);parish_id:Mapped[int]=mapped_column(ForeignKey("parishes.id",ondelete="RESTRICT"),nullable=False);community_id:Mapped[UUID|None]=mapped_column(ForeignKey("communities.id",ondelete="RESTRICT"));sector_id:Mapped[UUID|None]=mapped_column(ForeignKey("sectors.id",ondelete="RESTRICT"));created_by_user_id:Mapped[UUID]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"),nullable=False);is_active:Mapped[bool]=mapped_column(Boolean,default=True,server_default="true",nullable=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),nullable=False);updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),onupdate=func.now(),nullable=False)
class Commitment(Base):
    __tablename__="commitments";__table_args__=(CheckConstraint("priority IN ('LOW','MEDIUM','HIGH','CRITICAL')",name="priority"),CheckConstraint("status IN ('PENDING','IN_PROGRESS','COMPLETED','CANCELLED')",name="status"),CheckConstraint("status='COMPLETED' OR completed_date IS NULL",name="completed_date_status"),Index("ix_commitments_campaign_id","campaign_id"),Index("ix_commitments_status","status"),Index("ix_commitments_priority","priority"),Index("ix_commitments_due_date","due_date"),Index("ix_commitments_responsible_user_id","responsible_user_id"),Index("ix_commitments_parish_id","parish_id"),Index("ix_commitments_campaign_status","campaign_id","status"),Index("ix_commitments_campaign_due_date","campaign_id","due_date"))
    id:Mapped[UUID]=mapped_column(Uuid(as_uuid=True),primary_key=True,default=uuid4);campaign_id:Mapped[UUID]=mapped_column(ForeignKey("campaigns.id",ondelete="RESTRICT"),nullable=False);activity_id:Mapped[UUID|None]=mapped_column(ForeignKey("territorial_activities.id",ondelete="RESTRICT"));title:Mapped[str]=mapped_column(String(180),nullable=False);description:Mapped[str|None]=mapped_column(Text);priority:Mapped[str]=mapped_column(String(20),nullable=False);status:Mapped[str]=mapped_column(String(20),nullable=False);due_date:Mapped[date|None]=mapped_column(Date);completed_date:Mapped[date|None]=mapped_column(Date);responsible_user_id:Mapped[UUID|None]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"));parish_id:Mapped[int]=mapped_column(ForeignKey("parishes.id",ondelete="RESTRICT"),nullable=False);community_id:Mapped[UUID|None]=mapped_column(ForeignKey("communities.id",ondelete="RESTRICT"));sector_id:Mapped[UUID|None]=mapped_column(ForeignKey("sectors.id",ondelete="RESTRICT"));created_by_user_id:Mapped[UUID]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"),nullable=False);is_active:Mapped[bool]=mapped_column(Boolean,default=True,server_default="true",nullable=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),nullable=False);updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),onupdate=func.now(),nullable=False)
class ActivityEvidence(Base):
    __tablename__="activity_evidence";__table_args__=(CheckConstraint("evidence_type IN ('PHOTO','VIDEO','DOCUMENT','NEWS_LINK','SOCIAL_LINK','OTHER')",name="evidence_type"),Index("ix_activity_evidence_activity_id","activity_id"),Index("ix_activity_evidence_evidence_type","evidence_type"),Index("ix_activity_evidence_is_active","is_active"))
    id:Mapped[UUID]=mapped_column(Uuid(as_uuid=True),primary_key=True,default=uuid4);activity_id:Mapped[UUID]=mapped_column(ForeignKey("territorial_activities.id",ondelete="RESTRICT"),nullable=False);evidence_type:Mapped[str]=mapped_column(String(20),nullable=False);title:Mapped[str]=mapped_column(String(180),nullable=False);description:Mapped[str|None]=mapped_column(Text);url:Mapped[str]=mapped_column(String(1000),nullable=False);evidence_date:Mapped[date|None]=mapped_column(Date);uploaded_by_user_id:Mapped[UUID]=mapped_column(ForeignKey("users.id",ondelete="RESTRICT"),nullable=False);is_active:Mapped[bool]=mapped_column(Boolean,default=True,server_default="true",nullable=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),nullable=False);updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),onupdate=func.now(),nullable=False)
