from datetime import date,datetime
from decimal import Decimal
from uuid import UUID,uuid4
from sqlalchemy import Boolean,CheckConstraint,Date,DateTime,ForeignKey,Index,Integer,Numeric,String,Text,UniqueConstraint,Uuid,func
from sqlalchemy.orm import Mapped,mapped_column,relationship
from app.db.base import Base

class TechnicalFields:
    created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),nullable=False)
    updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),onupdate=func.now(),nullable=False)

class Survey(TechnicalFields,Base):
    __tablename__='surveys';__table_args__=(CheckConstraint("status IN ('DRAFT','PUBLISHED','CLOSED','ARCHIVED')",name='status'),CheckConstraint("target_scope IN ('CANTON','PARISH','COMMUNITY','SECTOR','ACTIVITY')",name='target_scope'),CheckConstraint('anonymous_only = true',name='anonymous_only'),CheckConstraint('start_date IS NULL OR end_date IS NULL OR start_date <= end_date',name='date_range'),UniqueConstraint('campaign_id','slug',name='uq_surveys_campaign_slug'),Index('ix_surveys_campaign_id','campaign_id'),Index('ix_surveys_status','status'),Index('ix_surveys_slug','slug'),Index('ix_surveys_campaign_status','campaign_id','status'))
    id:Mapped[UUID]=mapped_column(Uuid(as_uuid=True),primary_key=True,default=uuid4);campaign_id:Mapped[UUID]=mapped_column(ForeignKey('campaigns.id',ondelete='RESTRICT'),nullable=False);title:Mapped[str]=mapped_column(String(180),nullable=False);slug:Mapped[str]=mapped_column(String(180),nullable=False);description:Mapped[str|None]=mapped_column(Text);instructions:Mapped[str|None]=mapped_column(Text);status:Mapped[str]=mapped_column(String(20),default='DRAFT',server_default='DRAFT',nullable=False);start_date:Mapped[date|None]=mapped_column(Date);end_date:Mapped[date|None]=mapped_column(Date);published_date:Mapped[date|None]=mapped_column(Date);closed_date:Mapped[date|None]=mapped_column(Date);target_scope:Mapped[str]=mapped_column(String(20),nullable=False);allow_multiple_submissions:Mapped[bool]=mapped_column(Boolean,default=True,server_default='true',nullable=False);anonymous_only:Mapped[bool]=mapped_column(Boolean,default=True,server_default='true',nullable=False);show_progress:Mapped[bool]=mapped_column(Boolean,default=True,server_default='true',nullable=False);thank_you_message:Mapped[str|None]=mapped_column(String(500));created_by_user_id:Mapped[UUID]=mapped_column(ForeignKey('users.id',ondelete='RESTRICT'),nullable=False);is_active:Mapped[bool]=mapped_column(Boolean,default=True,server_default='true',nullable=False)
    sections:Mapped[list['SurveySection']]=relationship(back_populates='survey',order_by='SurveySection.display_order')

class SurveySection(TechnicalFields,Base):
    __tablename__='survey_sections';__table_args__=(CheckConstraint('display_order >= 0',name='display_order'),Index('ix_survey_sections_survey_id','survey_id'))
    id:Mapped[UUID]=mapped_column(Uuid(as_uuid=True),primary_key=True,default=uuid4);survey_id:Mapped[UUID]=mapped_column(ForeignKey('surveys.id',ondelete='RESTRICT'),nullable=False);title:Mapped[str]=mapped_column(String(180),nullable=False);description:Mapped[str|None]=mapped_column(Text);display_order:Mapped[int]=mapped_column(Integer,default=0,server_default='0',nullable=False);is_active:Mapped[bool]=mapped_column(Boolean,default=True,server_default='true',nullable=False)
    survey:Mapped[Survey]=relationship(back_populates='sections');questions:Mapped[list['SurveyQuestion']]=relationship(back_populates='section',order_by='SurveyQuestion.display_order')

class SurveyQuestion(TechnicalFields,Base):
    __tablename__='survey_questions';__table_args__=(CheckConstraint("question_type IN ('SINGLE_CHOICE','MULTIPLE_CHOICE','YES_NO','SHORT_TEXT','LONG_TEXT','INTEGER','DECIMAL','RATING')",name='type'),CheckConstraint('display_order >= 0',name='display_order'),CheckConstraint('min_value IS NULL OR max_value IS NULL OR min_value <= max_value',name='numeric_range'),CheckConstraint('min_length IS NULL OR max_length IS NULL OR min_length <= max_length',name='length_range'),CheckConstraint('min_selections IS NULL OR max_selections IS NULL OR min_selections <= max_selections',name='selection_range'),CheckConstraint('rating_min IS NULL OR rating_max IS NULL OR rating_min < rating_max',name='rating_range'),UniqueConstraint('survey_id','code',name='uq_survey_questions_survey_code'),Index('ix_survey_questions_survey_id','survey_id'),Index('ix_survey_questions_section_id','section_id'),Index('ix_survey_questions_code','code'))
    id:Mapped[UUID]=mapped_column(Uuid(as_uuid=True),primary_key=True,default=uuid4);survey_id:Mapped[UUID]=mapped_column(ForeignKey('surveys.id',ondelete='RESTRICT'),nullable=False);section_id:Mapped[UUID]=mapped_column(ForeignKey('survey_sections.id',ondelete='RESTRICT'),nullable=False);code:Mapped[str]=mapped_column(String(80),nullable=False);question_text:Mapped[str]=mapped_column(Text,nullable=False);help_text:Mapped[str|None]=mapped_column(Text);question_type:Mapped[str]=mapped_column(String(30),nullable=False);is_required:Mapped[bool]=mapped_column(Boolean,default=False,server_default='false',nullable=False);display_order:Mapped[int]=mapped_column(Integer,default=0,server_default='0',nullable=False);allow_other:Mapped[bool]=mapped_column(Boolean,default=False,server_default='false',nullable=False);min_value:Mapped[Decimal|None]=mapped_column(Numeric(18,4));max_value:Mapped[Decimal|None]=mapped_column(Numeric(18,4));min_length:Mapped[int|None]=mapped_column(Integer);max_length:Mapped[int|None]=mapped_column(Integer);min_selections:Mapped[int|None]=mapped_column(Integer);max_selections:Mapped[int|None]=mapped_column(Integer);rating_min:Mapped[int|None]=mapped_column(Integer);rating_max:Mapped[int|None]=mapped_column(Integer);rating_min_label:Mapped[str|None]=mapped_column(String(100));rating_max_label:Mapped[str|None]=mapped_column(String(100));is_active:Mapped[bool]=mapped_column(Boolean,default=True,server_default='true',nullable=False)
    section:Mapped[SurveySection]=relationship(back_populates='questions');options:Mapped[list['SurveyOption']]=relationship(back_populates='question',order_by='SurveyOption.display_order')

class SurveyOption(TechnicalFields,Base):
    __tablename__='survey_options';__table_args__=(CheckConstraint('display_order >= 0',name='display_order'),UniqueConstraint('question_id','code',name='uq_survey_options_question_code'),Index('ix_survey_options_question_id','question_id'))
    id:Mapped[UUID]=mapped_column(Uuid(as_uuid=True),primary_key=True,default=uuid4);question_id:Mapped[UUID]=mapped_column(ForeignKey('survey_questions.id',ondelete='RESTRICT'),nullable=False);code:Mapped[str]=mapped_column(String(80),nullable=False);label:Mapped[str]=mapped_column(String(250),nullable=False);description:Mapped[str|None]=mapped_column(String(500));display_order:Mapped[int]=mapped_column(Integer,default=0,server_default='0',nullable=False);is_other:Mapped[bool]=mapped_column(Boolean,default=False,server_default='false',nullable=False);is_active:Mapped[bool]=mapped_column(Boolean,default=True,server_default='true',nullable=False)
    question:Mapped[SurveyQuestion]=relationship(back_populates='options')

class SurveyResponse(TechnicalFields,Base):
    __tablename__='survey_responses';__table_args__=(CheckConstraint("source_channel IN ('FIELD','WEB','QR','ACTIVITY','MANUAL_IMPORT','OTHER')",name='source_channel'),CheckConstraint("age_range IS NULL OR age_range IN ('UNDER_18','AGE_18_24','AGE_25_34','AGE_35_44','AGE_45_54','AGE_55_64','AGE_65_PLUS','NOT_PROVIDED')",name='age_range'),CheckConstraint('sector_id IS NULL OR community_id IS NOT NULL',name='sector_requires_community'),UniqueConstraint('survey_id','submission_key_hash',name='uq_survey_responses_survey_submission_hash'),Index('ix_survey_responses_survey_id','survey_id'),Index('ix_survey_responses_campaign_id','campaign_id'),Index('ix_survey_responses_response_date','response_date'),Index('ix_survey_responses_parish_id','parish_id'),Index('ix_survey_responses_community_id','community_id'),Index('ix_survey_responses_sector_id','sector_id'),Index('ix_survey_responses_source_channel','source_channel'),Index('ix_survey_responses_is_valid','is_valid'),Index('ix_survey_responses_survey_date','survey_id','response_date'),Index('ix_survey_responses_survey_parish','survey_id','parish_id'),Index('ix_survey_responses_submission_key_hash','submission_key_hash'))
    id:Mapped[UUID]=mapped_column(Uuid(as_uuid=True),primary_key=True,default=uuid4);survey_id:Mapped[UUID]=mapped_column(ForeignKey('surveys.id',ondelete='RESTRICT'),nullable=False);campaign_id:Mapped[UUID]=mapped_column(ForeignKey('campaigns.id',ondelete='RESTRICT'),nullable=False);response_date:Mapped[date]=mapped_column(Date,nullable=False);parish_id:Mapped[int]=mapped_column(ForeignKey('parishes.id',ondelete='RESTRICT'),nullable=False);community_id:Mapped[UUID|None]=mapped_column(ForeignKey('communities.id',ondelete='RESTRICT'));sector_id:Mapped[UUID|None]=mapped_column(ForeignKey('sectors.id',ondelete='RESTRICT'));activity_id:Mapped[UUID|None]=mapped_column(ForeignKey('territorial_activities.id',ondelete='RESTRICT'));source_channel:Mapped[str]=mapped_column(String(20),nullable=False);submission_key_hash:Mapped[str|None]=mapped_column(String(64));age_range:Mapped[str|None]=mapped_column(String(20));is_complete:Mapped[bool]=mapped_column(Boolean,default=True,server_default='true',nullable=False);is_valid:Mapped[bool]=mapped_column(Boolean,default=True,server_default='true',nullable=False);invalid_reason:Mapped[str|None]=mapped_column(String(500));created_by_user_id:Mapped[UUID|None]=mapped_column(ForeignKey('users.id',ondelete='RESTRICT'))
    answers:Mapped[list['SurveyAnswer']]=relationship(back_populates='response')

class SurveyAnswer(TechnicalFields,Base):
    __tablename__='survey_answers';__table_args__=(UniqueConstraint('response_id','question_id',name='uq_survey_answers_response_question'),Index('ix_survey_answers_response_id','response_id'),Index('ix_survey_answers_question_id','question_id'))
    id:Mapped[UUID]=mapped_column(Uuid(as_uuid=True),primary_key=True,default=uuid4);response_id:Mapped[UUID]=mapped_column(ForeignKey('survey_responses.id',ondelete='RESTRICT'),nullable=False);question_id:Mapped[UUID]=mapped_column(ForeignKey('survey_questions.id',ondelete='RESTRICT'),nullable=False);text_value:Mapped[str|None]=mapped_column(Text);integer_value:Mapped[int|None]=mapped_column(Integer);decimal_value:Mapped[Decimal|None]=mapped_column(Numeric(18,4));boolean_value:Mapped[bool|None]=mapped_column(Boolean);rating_value:Mapped[int|None]=mapped_column(Integer);other_text:Mapped[str|None]=mapped_column(Text)
    response:Mapped[SurveyResponse]=relationship(back_populates='answers');selected_options:Mapped[list[SurveyOption]]=relationship(secondary='survey_answer_options')

class SurveyAnswerOption(Base):
    __tablename__='survey_answer_options';answer_id:Mapped[UUID]=mapped_column(ForeignKey('survey_answers.id',ondelete='CASCADE'),primary_key=True);option_id:Mapped[UUID]=mapped_column(ForeignKey('survey_options.id',ondelete='RESTRICT'),primary_key=True)
