export type StudyType = 'GENERAL_SURVEY' | 'CNE_EXIT_POLL' | 'POLL' | 'TRACKING_POLL' | 'EXIT_POLL' | 'OTHER';
export type StudyStatus = 'DRAFT' | 'VALIDATED' | 'PUBLISHED' | 'ARCHIVED';
export type Study = {
  id: string;
  campaign_id: string;
  code: string;
  name: string;
  description?: string;
  study_type: StudyType;
  status: StudyStatus;
  fieldwork_start_date: string;
  fieldwork_end_date: string;
  publication_date?: string;
  geography_level: 'CANTON' | 'PARISH';
  sample_size_total: number;
  universe_description: string;
  sampling_method: string;
  collection_method: string;
  confidence_level?: number;
  margin_of_error?: number;
  pollster_name?: string;
  sponsor_name?: string;
  source_type: string;
  source_url?: string;
  source_name?: string;
  source_document?: string;
  notes?: string;
  is_official: boolean;
  study_series_code?: string;
  question_code: string;
  methodology_completeness: 'COMPLETE' | 'PARTIAL' | 'LIMITED';
  updated_at: string;
  territories?: Territory[];
  options?: Option[];
  results?: Result[];
  exit_poll_warning?: string;
};
export type Territory = {
  id: string;
  study_id: string;
  parish_id?: number;
  parish_name?: string;
  parish_dpa?: string;
  sample_size: number;
  margin_of_error?: number;
  coverage_notes?: string;
};
export type Option = {
  id: string;
  study_id: string;
  question_code: string;
  question_text: string;
  question_type: 'SINGLE_CHOICE' | 'MULTIPLE_CHOICE' | 'SCALE' | 'RATING' | 'VOTE_INTENTION';
  code: string;
  label: string;
  option_type: string;
  display_order: number;
};
export type Result = {
  id: string;
  study_id: string;
  study_territory_id: string;
  option_id: string;
  option_code: string;
  option_label: string;
  option_type: string;
  response_count?: number;
  percentage: number;
};
export type StudyPage = {
  items: Study[];
  page: number;
  page_size: number;
  total: number;
  total_pages: number;
};
