"""anonymous territorial surveys

Revision ID: 08c32cc3ff8c
Revises: d00e4cd30f04
Create Date: 2026-08-03 16:24:00.231532
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '08c32cc3ff8c'
down_revision: Union[str, None] = 'd00e4cd30f04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surveys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='DRAFT', nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('published_date', sa.Date(), nullable=True),
    sa.Column('closed_date', sa.Date(), nullable=True),
    sa.Column('target_scope', sa.String(length=20), nullable=False),
    sa.Column('allow_multiple_submissions', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('anonymous_only', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('show_progress', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('thank_you_message', sa.String(length=500), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT','PUBLISHED','CLOSED','ARCHIVED')", name=op.f('ck_surveys_status')),
    sa.CheckConstraint("target_scope IN ('CANTON','PARISH','COMMUNITY','SECTOR','ACTIVITY')", name=op.f('ck_surveys_target_scope')),
    sa.CheckConstraint('anonymous_only = true', name=op.f('ck_surveys_anonymous_only')),
    sa.CheckConstraint('start_date IS NULL OR end_date IS NULL OR start_date <= end_date', name=op.f('ck_surveys_date_range')),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_surveys_campaign_id_campaigns'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_surveys_created_by_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_surveys')),
    sa.UniqueConstraint('campaign_id', 'slug', name='uq_surveys_campaign_slug')
    )
    op.create_index('ix_surveys_campaign_id', 'surveys', ['campaign_id'], unique=False)
    op.create_index('ix_surveys_campaign_status', 'surveys', ['campaign_id', 'status'], unique=False)
    op.create_index('ix_surveys_slug', 'surveys', ['slug'], unique=False)
    op.create_index('ix_surveys_status', 'surveys', ['status'], unique=False)
    op.create_table('survey_sections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('survey_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('display_order >= 0', name=op.f('ck_survey_sections_display_order')),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], name=op.f('fk_survey_sections_survey_id_surveys'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_survey_sections'))
    )
    op.create_index('ix_survey_sections_survey_id', 'survey_sections', ['survey_id'], unique=False)
    op.create_table('survey_questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('survey_id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('help_text', sa.Text(), nullable=True),
    sa.Column('question_type', sa.String(length=30), nullable=False),
    sa.Column('is_required', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('allow_other', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('min_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('max_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('min_length', sa.Integer(), nullable=True),
    sa.Column('max_length', sa.Integer(), nullable=True),
    sa.Column('min_selections', sa.Integer(), nullable=True),
    sa.Column('max_selections', sa.Integer(), nullable=True),
    sa.Column('rating_min', sa.Integer(), nullable=True),
    sa.Column('rating_max', sa.Integer(), nullable=True),
    sa.Column('rating_min_label', sa.String(length=100), nullable=True),
    sa.Column('rating_max_label', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("question_type IN ('SINGLE_CHOICE','MULTIPLE_CHOICE','YES_NO','SHORT_TEXT','LONG_TEXT','INTEGER','DECIMAL','RATING')", name=op.f('ck_survey_questions_type')),
    sa.CheckConstraint('display_order >= 0', name=op.f('ck_survey_questions_display_order')),
    sa.CheckConstraint('min_length IS NULL OR max_length IS NULL OR min_length <= max_length', name=op.f('ck_survey_questions_length_range')),
    sa.CheckConstraint('min_selections IS NULL OR max_selections IS NULL OR min_selections <= max_selections', name=op.f('ck_survey_questions_selection_range')),
    sa.CheckConstraint('min_value IS NULL OR max_value IS NULL OR min_value <= max_value', name=op.f('ck_survey_questions_numeric_range')),
    sa.CheckConstraint('rating_min IS NULL OR rating_max IS NULL OR rating_min < rating_max', name=op.f('ck_survey_questions_rating_range')),
    sa.ForeignKeyConstraint(['section_id'], ['survey_sections.id'], name=op.f('fk_survey_questions_section_id_survey_sections'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], name=op.f('fk_survey_questions_survey_id_surveys'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_survey_questions')),
    sa.UniqueConstraint('survey_id', 'code', name='uq_survey_questions_survey_code')
    )
    op.create_index('ix_survey_questions_code', 'survey_questions', ['code'], unique=False)
    op.create_index('ix_survey_questions_section_id', 'survey_questions', ['section_id'], unique=False)
    op.create_index('ix_survey_questions_survey_id', 'survey_questions', ['survey_id'], unique=False)
    op.create_table('survey_options',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=250), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_other', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('display_order >= 0', name=op.f('ck_survey_options_display_order')),
    sa.ForeignKeyConstraint(['question_id'], ['survey_questions.id'], name=op.f('fk_survey_options_question_id_survey_questions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_survey_options')),
    sa.UniqueConstraint('question_id', 'code', name='uq_survey_options_question_code')
    )
    op.create_index('ix_survey_options_question_id', 'survey_options', ['question_id'], unique=False)
    op.create_table('survey_responses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('survey_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('response_date', sa.Date(), nullable=False),
    sa.Column('parish_id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Uuid(), nullable=True),
    sa.Column('sector_id', sa.Uuid(), nullable=True),
    sa.Column('activity_id', sa.Uuid(), nullable=True),
    sa.Column('source_channel', sa.String(length=20), nullable=False),
    sa.Column('submission_key_hash', sa.String(length=64), nullable=True),
    sa.Column('age_range', sa.String(length=20), nullable=True),
    sa.Column('is_complete', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_valid', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('invalid_reason', sa.String(length=500), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("age_range IS NULL OR age_range IN ('UNDER_18','AGE_18_24','AGE_25_34','AGE_35_44','AGE_45_54','AGE_55_64','AGE_65_PLUS','NOT_PROVIDED')", name=op.f('ck_survey_responses_age_range')),
    sa.CheckConstraint("source_channel IN ('FIELD','WEB','QR','ACTIVITY','MANUAL_IMPORT','OTHER')", name=op.f('ck_survey_responses_source_channel')),
    sa.CheckConstraint('sector_id IS NULL OR community_id IS NOT NULL', name=op.f('ck_survey_responses_sector_requires_community')),
    sa.ForeignKeyConstraint(['activity_id'], ['territorial_activities.id'], name=op.f('fk_survey_responses_activity_id_territorial_activities'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_survey_responses_campaign_id_campaigns'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], name=op.f('fk_survey_responses_community_id_communities'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_survey_responses_created_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parish_id'], ['parishes.id'], name=op.f('fk_survey_responses_parish_id_parishes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], name=op.f('fk_survey_responses_sector_id_sectors'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], name=op.f('fk_survey_responses_survey_id_surveys'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_survey_responses')),
    sa.UniqueConstraint('survey_id', 'submission_key_hash', name='uq_survey_responses_survey_submission_hash')
    )
    op.create_index('ix_survey_responses_campaign_id', 'survey_responses', ['campaign_id'], unique=False)
    op.create_index('ix_survey_responses_community_id', 'survey_responses', ['community_id'], unique=False)
    op.create_index('ix_survey_responses_is_valid', 'survey_responses', ['is_valid'], unique=False)
    op.create_index('ix_survey_responses_parish_id', 'survey_responses', ['parish_id'], unique=False)
    op.create_index('ix_survey_responses_response_date', 'survey_responses', ['response_date'], unique=False)
    op.create_index('ix_survey_responses_sector_id', 'survey_responses', ['sector_id'], unique=False)
    op.create_index('ix_survey_responses_source_channel', 'survey_responses', ['source_channel'], unique=False)
    op.create_index('ix_survey_responses_submission_key_hash', 'survey_responses', ['submission_key_hash'], unique=False)
    op.create_index('ix_survey_responses_survey_date', 'survey_responses', ['survey_id', 'response_date'], unique=False)
    op.create_index('ix_survey_responses_survey_id', 'survey_responses', ['survey_id'], unique=False)
    op.create_index('ix_survey_responses_survey_parish', 'survey_responses', ['survey_id', 'parish_id'], unique=False)
    op.create_table('survey_answers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('response_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('text_value', sa.Text(), nullable=True),
    sa.Column('integer_value', sa.Integer(), nullable=True),
    sa.Column('decimal_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('boolean_value', sa.Boolean(), nullable=True),
    sa.Column('rating_value', sa.Integer(), nullable=True),
    sa.Column('other_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['survey_questions.id'], name=op.f('fk_survey_answers_question_id_survey_questions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['response_id'], ['survey_responses.id'], name=op.f('fk_survey_answers_response_id_survey_responses'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_survey_answers')),
    sa.UniqueConstraint('response_id', 'question_id', name='uq_survey_answers_response_question')
    )
    op.create_index('ix_survey_answers_question_id', 'survey_answers', ['question_id'], unique=False)
    op.create_index('ix_survey_answers_response_id', 'survey_answers', ['response_id'], unique=False)
    op.create_table('survey_answer_options',
    sa.Column('answer_id', sa.Uuid(), nullable=False),
    sa.Column('option_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['survey_answers.id'], name=op.f('fk_survey_answer_options_answer_id_survey_answers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['option_id'], ['survey_options.id'], name=op.f('fk_survey_answer_options_option_id_survey_options'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('answer_id', 'option_id', name=op.f('pk_survey_answer_options'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('survey_answer_options')
    op.drop_index('ix_survey_answers_response_id', table_name='survey_answers')
    op.drop_index('ix_survey_answers_question_id', table_name='survey_answers')
    op.drop_table('survey_answers')
    op.drop_index('ix_survey_responses_survey_parish', table_name='survey_responses')
    op.drop_index('ix_survey_responses_survey_id', table_name='survey_responses')
    op.drop_index('ix_survey_responses_survey_date', table_name='survey_responses')
    op.drop_index('ix_survey_responses_submission_key_hash', table_name='survey_responses')
    op.drop_index('ix_survey_responses_source_channel', table_name='survey_responses')
    op.drop_index('ix_survey_responses_sector_id', table_name='survey_responses')
    op.drop_index('ix_survey_responses_response_date', table_name='survey_responses')
    op.drop_index('ix_survey_responses_parish_id', table_name='survey_responses')
    op.drop_index('ix_survey_responses_is_valid', table_name='survey_responses')
    op.drop_index('ix_survey_responses_community_id', table_name='survey_responses')
    op.drop_index('ix_survey_responses_campaign_id', table_name='survey_responses')
    op.drop_table('survey_responses')
    op.drop_index('ix_survey_options_question_id', table_name='survey_options')
    op.drop_table('survey_options')
    op.drop_index('ix_survey_questions_survey_id', table_name='survey_questions')
    op.drop_index('ix_survey_questions_section_id', table_name='survey_questions')
    op.drop_index('ix_survey_questions_code', table_name='survey_questions')
    op.drop_table('survey_questions')
    op.drop_index('ix_survey_sections_survey_id', table_name='survey_sections')
    op.drop_table('survey_sections')
    op.drop_index('ix_surveys_status', table_name='surveys')
    op.drop_index('ix_surveys_slug', table_name='surveys')
    op.drop_index('ix_surveys_campaign_status', table_name='surveys')
    op.drop_index('ix_surveys_campaign_id', table_name='surveys')
    op.drop_table('surveys')
    # ### end Alembic commands ###

