"""official historical and demographic data

Revision ID: 12cff41d3836
Revises: 08c32cc3ff8c
Create Date: 2026-08-03 16:55:07.290876
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '12cff41d3836'
down_revision: Union[str, None] = '08c32cc3ff8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('institution', sa.String(length=180), nullable=False),
    sa.Column('dataset_name', sa.String(length=250), nullable=False),
    sa.Column('dataset_type', sa.String(length=50), nullable=False),
    sa.Column('official_url', sa.String(length=1000), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('reference_date', sa.Date(), nullable=True),
    sa.Column('reference_year', sa.Integer(), nullable=True),
    sa.Column('license_or_terms', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_official', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("dataset_type IN ('CNE_ELECTORAL_RESULTS','CNE_CANDIDATES','CNE_POLITICAL_ORGANIZATIONS','CNE_TURNOUT','INEC_DEMOGRAPHIC_INDICATORS','INEC_POPULATION_PROJECTIONS','INEC_GEOGRAPHIC_CLASSIFIER','OTHER_AGGREGATED_OFFICIAL')", name=op.f('ck_data_sources_dataset_type')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_data_sources_created_by_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_sources'))
    )
    op.create_index('ix_data_sources_code', 'data_sources', ['code'], unique=True)
    op.create_table('data_import_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('dataset_type', sa.String(length=50), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_sha256', sa.String(length=64), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('validation_only', sa.Boolean(), nullable=False),
    sa.Column('rows_read', sa.Integer(), nullable=False),
    sa.Column('rows_valid', sa.Integer(), nullable=False),
    sa.Column('rows_inserted', sa.Integer(), nullable=False),
    sa.Column('rows_updated', sa.Integer(), nullable=False),
    sa.Column('rows_skipped', sa.Integer(), nullable=False),
    sa.Column('rows_failed', sa.Integer(), nullable=False),
    sa.Column('encoding_used', sa.String(length=30), nullable=True),
    sa.Column('delimiter_used', sa.String(length=5), nullable=True),
    sa.Column('mapping_profile', sa.String(length=100), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('executed_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('RECEIVED','VALIDATING','VALIDATED','IMPORTING','COMPLETED','FAILED','REJECTED')", name=op.f('ck_data_import_jobs_status')),
    sa.CheckConstraint('file_size_bytes >= 0 AND rows_read >= 0 AND rows_valid >= 0 AND rows_inserted >= 0 AND rows_updated >= 0 AND rows_skipped >= 0 AND rows_failed >= 0', name=op.f('ck_data_import_jobs_nonnegative_counts')),
    sa.ForeignKeyConstraint(['executed_by_user_id'], ['users.id'], name=op.f('fk_data_import_jobs_executed_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], name=op.f('fk_data_import_jobs_source_id_data_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_import_jobs'))
    )
    op.create_index('ix_data_import_jobs_dataset_type', 'data_import_jobs', ['dataset_type'], unique=False)
    op.create_index('ix_data_import_jobs_file_sha256', 'data_import_jobs', ['file_sha256'], unique=False)
    op.create_index('ix_data_import_jobs_source_id', 'data_import_jobs', ['source_id'], unique=False)
    op.create_index('ix_data_import_jobs_source_type_sha', 'data_import_jobs', ['source_id', 'dataset_type', 'file_sha256'], unique=False)
    op.create_index('ix_data_import_jobs_status', 'data_import_jobs', ['status'], unique=False)
    op.create_table('demographic_indicators',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('POPULATION','AGE','EDUCATION','EMPLOYMENT','HOUSING','WATER','SEWERAGE','INTERNET','MIGRATION','TRANSPORT','OTHER')", name=op.f('ck_demographic_indicators_category')),
    sa.CheckConstraint("unit IN ('COUNT','PERCENT','RATE','INDEX','YEARS','OTHER')", name=op.f('ck_demographic_indicators_unit')),
    sa.CheckConstraint("value_type IN ('INTEGER','DECIMAL')", name=op.f('ck_demographic_indicators_value_type')),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], name=op.f('fk_demographic_indicators_source_id_data_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_demographic_indicators'))
    )
    op.create_index('ix_demographic_indicators_code', 'demographic_indicators', ['code'], unique=True)
    op.create_table('electoral_processes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('process_type', sa.String(length=20), nullable=False),
    sa.Column('election_date', sa.Date(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("process_type IN ('SECTIONAL','GENERAL','REFERENDUM','CONSULTATION','OTHER')", name=op.f('ck_electoral_processes_process_type')),
    sa.CheckConstraint("status IN ('DRAFT','IMPORTED','VALIDATED','PUBLISHED','ARCHIVED')", name=op.f('ck_electoral_processes_status')),
    sa.CheckConstraint('year = EXTRACT(YEAR FROM election_date)', name=op.f('ck_electoral_processes_year_matches_date')),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], name=op.f('fk_electoral_processes_source_id_data_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_electoral_processes'))
    )
    op.create_index('ix_electoral_processes_code', 'electoral_processes', ['code'], unique=True)
    op.create_index('ix_electoral_processes_status', 'electoral_processes', ['status'], unique=False)
    op.create_index('ix_electoral_processes_type', 'electoral_processes', ['process_type'], unique=False)
    op.create_index('ix_electoral_processes_year', 'electoral_processes', ['year'], unique=False)
    op.create_table('political_organizations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_code', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('short_name', sa.String(length=100), nullable=True),
    sa.Column('organization_type', sa.String(length=100), nullable=True),
    sa.Column('list_number', sa.String(length=30), nullable=True),
    sa.Column('scope', sa.String(length=100), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], name=op.f('fk_political_organizations_source_id_data_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_political_organizations')),
    sa.UniqueConstraint('source_id', 'external_code', name='uq_political_organizations_source_code')
    )
    op.create_table('data_import_errors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('import_job_id', sa.Uuid(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=True),
    sa.Column('column_name', sa.String(length=100), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('rejected_value_preview', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['import_job_id'], ['data_import_jobs.id'], name=op.f('fk_data_import_errors_import_job_id_data_import_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_import_errors'))
    )
    op.create_index('ix_data_import_errors_import_job_id', 'data_import_errors', ['import_job_id'], unique=False)
    op.create_table('demographic_observations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('demographic_indicator_id', sa.Uuid(), nullable=False),
    sa.Column('geography_level', sa.String(length=20), nullable=False),
    sa.Column('province_id', sa.Integer(), nullable=True),
    sa.Column('canton_id', sa.Integer(), nullable=True),
    sa.Column('parish_id', sa.Integer(), nullable=True),
    sa.Column('reference_year', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('numerator', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('denominator', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('import_job_id', sa.Uuid(), nullable=False),
    sa.Column('is_official', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("geography_level IN ('PROVINCE','CANTON','PARISH')", name=op.f('ck_demographic_observations_level')),
    sa.CheckConstraint('denominator IS NULL OR denominator > 0', name=op.f('ck_demographic_observations_denominator_positive')),
    sa.CheckConstraint('reference_year BETWEEN 1900 AND 2200', name=op.f('ck_demographic_observations_year')),
    sa.ForeignKeyConstraint(['canton_id'], ['cantons.id'], name=op.f('fk_demographic_observations_canton_id_cantons')),
    sa.ForeignKeyConstraint(['demographic_indicator_id'], ['demographic_indicators.id'], name=op.f('fk_demographic_observations_demographic_indicator_id_demographic_indicators'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['import_job_id'], ['data_import_jobs.id'], name=op.f('fk_demographic_observations_import_job_id_data_import_jobs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parish_id'], ['parishes.id'], name=op.f('fk_demographic_observations_parish_id_parishes')),
    sa.ForeignKeyConstraint(['province_id'], ['provinces.id'], name=op.f('fk_demographic_observations_province_id_provinces')),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], name=op.f('fk_demographic_observations_source_id_data_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_demographic_observations')),
    sa.UniqueConstraint('demographic_indicator_id', 'geography_level', 'province_id', 'canton_id', 'parish_id', 'reference_year', 'source_id', name='uq_demographic_observations_key')
    )
    op.create_index('ix_demographic_observations_canton_id', 'demographic_observations', ['canton_id'], unique=False)
    op.create_index('ix_demographic_observations_indicator_id', 'demographic_observations', ['demographic_indicator_id'], unique=False)
    op.create_index('ix_demographic_observations_parish_id', 'demographic_observations', ['parish_id'], unique=False)
    op.create_index('ix_demographic_observations_source_id', 'demographic_observations', ['source_id'], unique=False)
    op.create_index('ix_demographic_observations_year', 'demographic_observations', ['reference_year'], unique=False)
    op.create_table('electoral_contests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('electoral_process_id', sa.Uuid(), nullable=False),
    sa.Column('office_type', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('vote_method', sa.String(length=20), nullable=False),
    sa.Column('province_id', sa.Integer(), nullable=True),
    sa.Column('canton_id', sa.Integer(), nullable=True),
    sa.Column('parish_id', sa.Integer(), nullable=True),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("office_type != 'MAYOR' OR canton_id IS NOT NULL", name=op.f('ck_electoral_contests_mayor_canton')),
    sa.CheckConstraint("office_type != 'PARISH_BOARD' OR parish_id IS NOT NULL", name=op.f('ck_electoral_contests_parish_board_parish')),
    sa.CheckConstraint("office_type IN ('MAYOR','URBAN_COUNCILOR','RURAL_COUNCILOR','PARISH_BOARD','PREFECTURE','OTHER')", name=op.f('ck_electoral_contests_office_type')),
    sa.CheckConstraint("vote_method IN ('SINGLE_CHOICE','MULTI_VOTE','LIST_VOTE','OTHER')", name=op.f('ck_electoral_contests_vote_method')),
    sa.CheckConstraint('seats >= 1', name=op.f('ck_electoral_contests_seats')),
    sa.ForeignKeyConstraint(['canton_id'], ['cantons.id'], name=op.f('fk_electoral_contests_canton_id_cantons')),
    sa.ForeignKeyConstraint(['electoral_process_id'], ['electoral_processes.id'], name=op.f('fk_electoral_contests_electoral_process_id_electoral_processes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parish_id'], ['parishes.id'], name=op.f('fk_electoral_contests_parish_id_parishes')),
    sa.ForeignKeyConstraint(['province_id'], ['provinces.id'], name=op.f('fk_electoral_contests_province_id_provinces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_electoral_contests')),
    sa.UniqueConstraint('electoral_process_id', 'office_type', 'province_id', 'canton_id', 'parish_id', 'name', name='uq_electoral_contests_equivalent')
    )
    op.create_index('ix_electoral_contests_process_id', 'electoral_contests', ['electoral_process_id'], unique=False)
    op.create_table('electoral_geographies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('electoral_process_id', sa.Uuid(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('external_code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('province_id', sa.Integer(), nullable=True),
    sa.Column('canton_id', sa.Integer(), nullable=True),
    sa.Column('parish_id', sa.Integer(), nullable=True),
    sa.Column('zone_code', sa.String(length=50), nullable=True),
    sa.Column('precinct_code', sa.String(length=50), nullable=True),
    sa.Column('jrv_code', sa.String(length=50), nullable=True),
    sa.Column('is_mapped', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("level IN ('PROVINCE','CANTON','PARISH','ZONE','PRECINCT','JRV')", name=op.f('ck_electoral_geographies_level')),
    sa.ForeignKeyConstraint(['canton_id'], ['cantons.id'], name=op.f('fk_electoral_geographies_canton_id_cantons')),
    sa.ForeignKeyConstraint(['electoral_process_id'], ['electoral_processes.id'], name=op.f('fk_electoral_geographies_electoral_process_id_electoral_processes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_id'], ['electoral_geographies.id'], name=op.f('fk_electoral_geographies_parent_id_electoral_geographies')),
    sa.ForeignKeyConstraint(['parish_id'], ['parishes.id'], name=op.f('fk_electoral_geographies_parish_id_parishes')),
    sa.ForeignKeyConstraint(['province_id'], ['provinces.id'], name=op.f('fk_electoral_geographies_province_id_provinces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_electoral_geographies')),
    sa.UniqueConstraint('electoral_process_id', 'level', 'external_code', name='uq_electoral_geographies_process_level_code')
    )
    op.create_index('ix_electoral_geographies_canton_id', 'electoral_geographies', ['canton_id'], unique=False)
    op.create_index('ix_electoral_geographies_external_code', 'electoral_geographies', ['external_code'], unique=False)
    op.create_index('ix_electoral_geographies_level', 'electoral_geographies', ['level'], unique=False)
    op.create_index('ix_electoral_geographies_parish_id', 'electoral_geographies', ['parish_id'], unique=False)
    op.create_index('ix_electoral_geographies_process_id', 'electoral_geographies', ['electoral_process_id'], unique=False)
    op.create_table('electoral_candidates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('electoral_contest_id', sa.Uuid(), nullable=False),
    sa.Column('political_organization_id', sa.Uuid(), nullable=True),
    sa.Column('external_code', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=250), nullable=False),
    sa.Column('display_name', sa.String(length=250), nullable=True),
    sa.Column('list_number', sa.String(length=30), nullable=True),
    sa.Column('ballot_order', sa.Integer(), nullable=True),
    sa.Column('is_winner', sa.Boolean(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['electoral_contest_id'], ['electoral_contests.id'], name=op.f('fk_electoral_candidates_electoral_contest_id_electoral_contests'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['political_organization_id'], ['political_organizations.id'], name=op.f('fk_electoral_candidates_political_organization_id_political_organizations')),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], name=op.f('fk_electoral_candidates_source_id_data_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_electoral_candidates')),
    sa.UniqueConstraint('electoral_contest_id', 'external_code', name='uq_electoral_candidates_contest_code')
    )
    op.create_table('electoral_turnout',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('electoral_contest_id', sa.Uuid(), nullable=False),
    sa.Column('electoral_geography_id', sa.Uuid(), nullable=False),
    sa.Column('registered_voters', sa.Integer(), nullable=False),
    sa.Column('ballots_cast', sa.Integer(), nullable=False),
    sa.Column('valid_votes', sa.Integer(), nullable=False),
    sa.Column('blank_votes', sa.Integer(), nullable=False),
    sa.Column('null_votes', sa.Integer(), nullable=False),
    sa.Column('other_votes', sa.Integer(), nullable=False),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('import_job_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ballots_cast <= registered_voters', name=op.f('ck_electoral_turnout_cast_lte_registered')),
    sa.CheckConstraint('registered_voters>=0 AND ballots_cast>=0 AND valid_votes>=0 AND blank_votes>=0 AND null_votes>=0 AND other_votes>=0', name=op.f('ck_electoral_turnout_nonnegative')),
    sa.ForeignKeyConstraint(['electoral_contest_id'], ['electoral_contests.id'], name=op.f('fk_electoral_turnout_electoral_contest_id_electoral_contests'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['electoral_geography_id'], ['electoral_geographies.id'], name=op.f('fk_electoral_turnout_electoral_geography_id_electoral_geographies'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['import_job_id'], ['data_import_jobs.id'], name=op.f('fk_electoral_turnout_import_job_id_data_import_jobs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], name=op.f('fk_electoral_turnout_source_id_data_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_electoral_turnout')),
    sa.UniqueConstraint('electoral_contest_id', 'electoral_geography_id', name='uq_electoral_turnout_contest_geography')
    )
    op.create_index('ix_electoral_turnout_contest_geography', 'electoral_turnout', ['electoral_contest_id', 'electoral_geography_id'], unique=False)
    op.create_index('ix_electoral_turnout_contest_id', 'electoral_turnout', ['electoral_contest_id'], unique=False)
    op.create_index('ix_electoral_turnout_geography_id', 'electoral_turnout', ['electoral_geography_id'], unique=False)
    op.create_table('electoral_candidate_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('electoral_contest_id', sa.Uuid(), nullable=False),
    sa.Column('electoral_geography_id', sa.Uuid(), nullable=False),
    sa.Column('electoral_candidate_id', sa.Uuid(), nullable=False),
    sa.Column('votes', sa.Integer(), nullable=False),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('import_job_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('votes >= 0', name=op.f('ck_electoral_candidate_results_votes_nonnegative')),
    sa.ForeignKeyConstraint(['electoral_candidate_id'], ['electoral_candidates.id'], name=op.f('fk_electoral_candidate_results_electoral_candidate_id_electoral_candidates'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['electoral_contest_id'], ['electoral_contests.id'], name=op.f('fk_electoral_candidate_results_electoral_contest_id_electoral_contests'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['electoral_geography_id'], ['electoral_geographies.id'], name=op.f('fk_electoral_candidate_results_electoral_geography_id_electoral_geographies'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['import_job_id'], ['data_import_jobs.id'], name=op.f('fk_electoral_candidate_results_import_job_id_data_import_jobs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], name=op.f('fk_electoral_candidate_results_source_id_data_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_electoral_candidate_results')),
    sa.UniqueConstraint('electoral_contest_id', 'electoral_geography_id', 'electoral_candidate_id', name='uq_candidate_results_contest_geography_candidate')
    )
    op.create_index('ix_candidate_results_candidate_id', 'electoral_candidate_results', ['electoral_candidate_id'], unique=False)
    op.create_index('ix_candidate_results_contest_id', 'electoral_candidate_results', ['electoral_contest_id'], unique=False)
    op.create_index('ix_candidate_results_geography_id', 'electoral_candidate_results', ['electoral_geography_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_candidate_results_geography_id', table_name='electoral_candidate_results')
    op.drop_index('ix_candidate_results_contest_id', table_name='electoral_candidate_results')
    op.drop_index('ix_candidate_results_candidate_id', table_name='electoral_candidate_results')
    op.drop_table('electoral_candidate_results')
    op.drop_index('ix_electoral_turnout_geography_id', table_name='electoral_turnout')
    op.drop_index('ix_electoral_turnout_contest_id', table_name='electoral_turnout')
    op.drop_index('ix_electoral_turnout_contest_geography', table_name='electoral_turnout')
    op.drop_table('electoral_turnout')
    op.drop_table('electoral_candidates')
    op.drop_index('ix_electoral_geographies_process_id', table_name='electoral_geographies')
    op.drop_index('ix_electoral_geographies_parish_id', table_name='electoral_geographies')
    op.drop_index('ix_electoral_geographies_level', table_name='electoral_geographies')
    op.drop_index('ix_electoral_geographies_external_code', table_name='electoral_geographies')
    op.drop_index('ix_electoral_geographies_canton_id', table_name='electoral_geographies')
    op.drop_table('electoral_geographies')
    op.drop_index('ix_electoral_contests_process_id', table_name='electoral_contests')
    op.drop_table('electoral_contests')
    op.drop_index('ix_demographic_observations_year', table_name='demographic_observations')
    op.drop_index('ix_demographic_observations_source_id', table_name='demographic_observations')
    op.drop_index('ix_demographic_observations_parish_id', table_name='demographic_observations')
    op.drop_index('ix_demographic_observations_indicator_id', table_name='demographic_observations')
    op.drop_index('ix_demographic_observations_canton_id', table_name='demographic_observations')
    op.drop_table('demographic_observations')
    op.drop_index('ix_data_import_errors_import_job_id', table_name='data_import_errors')
    op.drop_table('data_import_errors')
    op.drop_table('political_organizations')
    op.drop_index('ix_electoral_processes_year', table_name='electoral_processes')
    op.drop_index('ix_electoral_processes_type', table_name='electoral_processes')
    op.drop_index('ix_electoral_processes_status', table_name='electoral_processes')
    op.drop_index('ix_electoral_processes_code', table_name='electoral_processes')
    op.drop_table('electoral_processes')
    op.drop_index('ix_demographic_indicators_code', table_name='demographic_indicators')
    op.drop_table('demographic_indicators')
    op.drop_index('ix_data_import_jobs_status', table_name='data_import_jobs')
    op.drop_index('ix_data_import_jobs_source_type_sha', table_name='data_import_jobs')
    op.drop_index('ix_data_import_jobs_source_id', table_name='data_import_jobs')
    op.drop_index('ix_data_import_jobs_file_sha256', table_name='data_import_jobs')
    op.drop_index('ix_data_import_jobs_dataset_type', table_name='data_import_jobs')
    op.drop_table('data_import_jobs')
    op.drop_index('ix_data_sources_code', table_name='data_sources')
    op.drop_table('data_sources')
    # ### end Alembic commands ###

