"""public intelligence v2.5

Revision ID: 20260814_0001
Revises: 20260813_0001
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision="20260814_0001";down_revision="20260813_0001";branch_labels=None;depends_on=None
json_type=postgresql.JSONB(astext_type=sa.Text())

def upgrade():
    op.create_table("public_sources",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("campaign_id",sa.Uuid(),sa.ForeignKey("campaigns.id",ondelete="RESTRICT"),nullable=False),sa.Column("code",sa.String(80),nullable=False),sa.Column("name",sa.String(180),nullable=False),sa.Column("publisher",sa.String(180),nullable=False),sa.Column("source_type",sa.String(40),nullable=False),sa.Column("base_url",sa.String(1000),nullable=False),sa.Column("feed_url",sa.String(1000)),sa.Column("api_url",sa.String(1000)),sa.Column("jurisdiction",sa.String(180)),sa.Column("country",sa.String(80),nullable=False,server_default="EC"),sa.Column("province",sa.String(120)),sa.Column("canton",sa.String(120)),sa.Column("official",sa.Boolean(),nullable=False,server_default=sa.false()),sa.Column("active",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("retrieval_method",sa.String(30),nullable=False),sa.Column("refresh_interval_minutes",sa.Integer()),sa.Column("terms_notes",sa.Text()),sa.Column("license_notes",sa.Text()),sa.Column("credential_reference",sa.String(180)),sa.Column("adapter_config",json_type,nullable=False,server_default="{}"),sa.Column("etag",sa.String(255)),sa.Column("last_modified",sa.String(255)),sa.Column("last_fetch_at",sa.DateTime(timezone=True)),sa.Column("last_success_at",sa.DateTime(timezone=True)),sa.Column("consecutive_failures",sa.Integer(),nullable=False,server_default="0"),sa.Column("items_last_fetch",sa.Integer(),nullable=False,server_default="0"),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.UniqueConstraint("campaign_id","code",name="uq_public_sources_campaign_code"))
    op.create_index("ix_public_sources_campaign_active","public_sources",["campaign_id","active"])
    op.create_table("public_intelligence_items",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("source_id",sa.Uuid(),sa.ForeignKey("public_sources.id",ondelete="RESTRICT"),nullable=False),sa.Column("external_id",sa.String(500)),sa.Column("title",sa.String(500),nullable=False),sa.Column("summary",sa.Text()),sa.Column("item_type",sa.String(40),nullable=False),sa.Column("url",sa.String(2000),nullable=False),sa.Column("canonical_url",sa.String(2000),nullable=False),sa.Column("published_at",sa.DateTime(timezone=True)),sa.Column("fetched_at",sa.DateTime(timezone=True),nullable=False),sa.Column("author",sa.String(255)),sa.Column("content_excerpt",sa.Text()),sa.Column("normalized_text",sa.Text()),sa.Column("language",sa.String(12),nullable=False,server_default="es"),sa.Column("content_hash",sa.String(64),nullable=False),sa.Column("status",sa.String(20),nullable=False,server_default="ACTIVE"),sa.Column("original_metadata",json_type,nullable=False,server_default="{}"),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.UniqueConstraint("source_id","canonical_url",name="uq_public_items_source_canonical"))
    for name,cols in (("ix_public_items_source",["source_id"]),("ix_public_items_published",["published_at"]),("ix_public_items_status",["status"]),("ix_public_items_hash",["content_hash"])):op.create_index(name,"public_intelligence_items",cols)
    op.create_table("public_item_revisions",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("item_id",sa.Uuid(),sa.ForeignKey("public_intelligence_items.id",ondelete="CASCADE"),nullable=False),sa.Column("content_hash",sa.String(64),nullable=False),sa.Column("fetched_at",sa.DateTime(timezone=True),nullable=False),sa.Column("change_detected",sa.Boolean(),nullable=False),sa.Column("metadata_snapshot",json_type,nullable=False),sa.UniqueConstraint("item_id","content_hash",name="uq_public_item_revision_hash"));op.create_index("ix_public_item_revisions_item","public_item_revisions",["item_id"])
    op.create_table("public_source_fetch_runs",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("source_id",sa.Uuid(),sa.ForeignKey("public_sources.id",ondelete="RESTRICT"),nullable=False),sa.Column("started_at",sa.DateTime(timezone=True),nullable=False),sa.Column("finished_at",sa.DateTime(timezone=True)),sa.Column("status",sa.String(20),nullable=False),sa.Column("items_discovered",sa.Integer(),nullable=False,server_default="0"),sa.Column("items_created",sa.Integer(),nullable=False,server_default="0"),sa.Column("items_updated",sa.Integer(),nullable=False,server_default="0"),sa.Column("items_unchanged",sa.Integer(),nullable=False,server_default="0"),sa.Column("items_failed",sa.Integer(),nullable=False,server_default="0"),sa.Column("error_summary",sa.Text()),sa.Column("trigger_type",sa.String(20),nullable=False));op.create_index("ix_public_fetch_runs_source_started","public_source_fetch_runs",["source_id","started_at"])
    op.create_table("public_topics",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("code",sa.String(80),nullable=False,unique=True),sa.Column("name",sa.String(140),nullable=False),sa.Column("keywords",json_type,nullable=False,server_default="[]"),sa.Column("active",sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table("public_item_topics",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("item_id",sa.Uuid(),sa.ForeignKey("public_intelligence_items.id",ondelete="CASCADE"),nullable=False),sa.Column("topic_id",sa.Integer(),sa.ForeignKey("public_topics.id",ondelete="RESTRICT"),nullable=False),sa.Column("association_method",sa.String(30),nullable=False),sa.UniqueConstraint("item_id","topic_id",name="uq_public_item_topics_item_topic"))
    op.create_table("public_item_territories",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("item_id",sa.Uuid(),sa.ForeignKey("public_intelligence_items.id",ondelete="CASCADE"),nullable=False),sa.Column("territory_level",sa.String(20),nullable=False),sa.Column("parish_id",sa.Integer(),sa.ForeignKey("parishes.id",ondelete="RESTRICT")),sa.Column("association_method",sa.String(30),nullable=False),sa.Column("confidence",sa.Float()),sa.UniqueConstraint("item_id","parish_id",name="uq_public_item_territories_item_parish"));op.create_index("ix_public_item_territories_parish","public_item_territories",["parish_id"])
    op.create_table("public_item_need_links",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("item_id",sa.Uuid(),sa.ForeignKey("public_intelligence_items.id",ondelete="CASCADE"),nullable=False),sa.Column("need_id",sa.Uuid(),sa.ForeignKey("citizen_needs.id",ondelete="RESTRICT"),nullable=False),sa.Column("linked_by_user_id",sa.Uuid(),sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.UniqueConstraint("item_id","need_id",name="uq_public_item_need_links_item_need"))
    topics={"VIALIDAD":["vía","carretera","asfalto","pavimentación","bacheo","puente"],"AGUA_SANITATION":["agua potable","alcantarillado","saneamiento"],"SECURITY":["seguridad"],"HEALTH":["salud"],"EDUCATION":["educación"],"PUBLIC_WORKS":["obra pública","proyecto"],"BUDGET":["presupuesto"],"OTHER":[]}
    table=sa.table("public_topics",sa.column("code",sa.String),sa.column("name",sa.String),sa.column("keywords",json_type),sa.column("active",sa.Boolean))
    op.bulk_insert(table,[{"code":k,"name":k.replace("_"," ").title(),"keywords":v,"active":True} for k,v in topics.items()])

def downgrade():
    for table in ("public_item_need_links","public_item_territories","public_item_topics","public_topics","public_source_fetch_runs","public_item_revisions","public_intelligence_items","public_sources"):op.drop_table(table)
