"""Election Day Operations module: polling places, boards, assignments, incidents, documents.

Revision ID: 20260908_0001
Revises: 20260907_0001
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '20260908_0001'
down_revision: Union[str, None] = '20260907_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('election_day_operations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('electoral_process_id', sa.Uuid(), nullable=False),
    sa.Column('election_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='PREPARATION', nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opened_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('closed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PREPARATION','ACTIVE','CLOSED')", name=op.f('ck_election_day_operations_status')),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_election_day_operations_campaign_id_campaigns'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['closed_by_user_id'], ['users.id'], name=op.f('fk_election_day_operations_closed_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['electoral_process_id'], ['electoral_processes.id'], name=op.f('fk_election_day_operations_electoral_process_id_electoral_processes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['opened_by_user_id'], ['users.id'], name=op.f('fk_election_day_operations_opened_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_election_day_operations_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_election_day_operations')),
    sa.UniqueConstraint('campaign_id', 'electoral_process_id', name='uq_election_day_operations_campaign_process')
    )
    op.create_index('ix_election_day_operations_campaign_id', 'election_day_operations', ['campaign_id'], unique=False)
    op.create_index('ix_election_day_operations_electoral_process_id', 'election_day_operations', ['electoral_process_id'], unique=False)
    op.create_index('ix_election_day_operations_status', 'election_day_operations', ['status'], unique=False)
    op.create_table('polling_places',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('electoral_process_id', sa.Uuid(), nullable=False),
    sa.Column('province_id', sa.Integer(), nullable=False),
    sa.Column('canton_id', sa.Integer(), nullable=False),
    sa.Column('parish_id', sa.Integer(), nullable=False),
    sa.Column('official_code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=220), nullable=False),
    sa.Column('address', sa.String(length=400), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('data_source_id', sa.Uuid(), nullable=True),
    sa.Column('import_job_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['canton_id'], ['cantons.id'], name=op.f('fk_polling_places_canton_id_cantons'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], name=op.f('fk_polling_places_data_source_id_data_sources'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['electoral_process_id'], ['electoral_processes.id'], name=op.f('fk_polling_places_electoral_process_id_electoral_processes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['import_job_id'], ['data_import_jobs.id'], name=op.f('fk_polling_places_import_job_id_data_import_jobs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parish_id'], ['parishes.id'], name=op.f('fk_polling_places_parish_id_parishes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['province_id'], ['provinces.id'], name=op.f('fk_polling_places_province_id_provinces'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_polling_places')),
    sa.UniqueConstraint('electoral_process_id', 'official_code', name='uq_polling_places_process_code')
    )
    op.create_index('ix_polling_places_canton_id', 'polling_places', ['canton_id'], unique=False)
    op.create_index('ix_polling_places_electoral_process_id', 'polling_places', ['electoral_process_id'], unique=False)
    op.create_index('ix_polling_places_is_active', 'polling_places', ['is_active'], unique=False)
    op.create_index('ix_polling_places_parish_id', 'polling_places', ['parish_id'], unique=False)
    op.create_table('electoral_boards',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('polling_place_id', sa.Uuid(), nullable=False),
    sa.Column('official_code', sa.String(length=40), nullable=False),
    sa.Column('board_number', sa.Integer(), nullable=False),
    sa.Column('sex_category', sa.String(length=20), nullable=True),
    sa.Column('registered_voters', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('data_source_id', sa.Uuid(), nullable=True),
    sa.Column('import_job_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('registered_voters IS NULL OR registered_voters >= 0', name=op.f('ck_electoral_boards_registered_voters_nonnegative')),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], name=op.f('fk_electoral_boards_data_source_id_data_sources'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['import_job_id'], ['data_import_jobs.id'], name=op.f('fk_electoral_boards_import_job_id_data_import_jobs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['polling_place_id'], ['polling_places.id'], name=op.f('fk_electoral_boards_polling_place_id_polling_places'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_electoral_boards')),
    sa.UniqueConstraint('polling_place_id', 'official_code', name='uq_electoral_boards_place_code')
    )
    op.create_index('ix_electoral_boards_is_active', 'electoral_boards', ['is_active'], unique=False)
    op.create_index('ix_electoral_boards_polling_place_id', 'electoral_boards', ['polling_place_id'], unique=False)
    op.create_table('election_day_assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('operation_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('polling_place_id', sa.Uuid(), nullable=False),
    sa.Column('board_id', sa.Uuid(), nullable=True),
    sa.Column('assignment_role', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='ASSIGNED', nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checkin_latitude', sa.Float(), nullable=True),
    sa.Column('checkin_longitude', sa.Float(), nullable=True),
    sa.Column('checkin_client_generated_id', sa.Uuid(), nullable=True),
    sa.Column('checkin_offline_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_assignment_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("assignment_role IN ('POLLING_PLACE_COORDINATOR','BOARD_DELEGATE','MOBILE_SUPPORT')", name=op.f('ck_election_day_assignments_assignment_role')),
    sa.CheckConstraint("status IN ('ASSIGNED','CONFIRMED','CHECKED_IN','ABSENT','REPLACED','COMPLETED')", name=op.f('ck_election_day_assignments_status')),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.id'], name=op.f('fk_election_day_assignments_assigned_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['board_id'], ['electoral_boards.id'], name=op.f('fk_election_day_assignments_board_id_electoral_boards'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['operation_id'], ['election_day_operations.id'], name=op.f('fk_election_day_assignments_operation_id_election_day_operations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['polling_place_id'], ['polling_places.id'], name=op.f('fk_election_day_assignments_polling_place_id_polling_places'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['replaced_by_assignment_id'], ['election_day_assignments.id'], name=op.f('fk_election_day_assignments_replaced_by_assignment_id_election_day_assignments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_election_day_assignments_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_election_day_assignments'))
    )
    op.create_index('ix_election_day_assignments_board_id', 'election_day_assignments', ['board_id'], unique=False)
    op.create_index('ix_election_day_assignments_operation_id', 'election_day_assignments', ['operation_id'], unique=False)
    op.create_index('ix_election_day_assignments_polling_place_id', 'election_day_assignments', ['polling_place_id'], unique=False)
    op.create_index('ix_election_day_assignments_status', 'election_day_assignments', ['status'], unique=False)
    op.create_index('ix_election_day_assignments_user_id', 'election_day_assignments', ['user_id'], unique=False)
    op.create_table('election_day_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('operation_id', sa.Uuid(), nullable=False),
    sa.Column('polling_place_id', sa.Uuid(), nullable=False),
    sa.Column('board_id', sa.Uuid(), nullable=True),
    sa.Column('document_type', sa.String(length=30), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('uploaded_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='RECEIVED', nullable=False),
    sa.Column('client_generated_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("document_type IN ('ACTA_COPY','INCIDENT_DOCUMENT','OTHER')", name=op.f('ck_election_day_documents_document_type')),
    sa.CheckConstraint("status IN ('RECEIVED','REQUIRES_REVIEW','VALIDATED')", name=op.f('ck_election_day_documents_status')),
    sa.ForeignKeyConstraint(['board_id'], ['electoral_boards.id'], name=op.f('fk_election_day_documents_board_id_electoral_boards'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['operation_id'], ['election_day_operations.id'], name=op.f('fk_election_day_documents_operation_id_election_day_operations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['polling_place_id'], ['polling_places.id'], name=op.f('fk_election_day_documents_polling_place_id_polling_places'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], name=op.f('fk_election_day_documents_uploaded_by_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_election_day_documents'))
    )
    op.create_index('ix_election_day_documents_board_id', 'election_day_documents', ['board_id'], unique=False)
    op.create_index('ix_election_day_documents_operation_id', 'election_day_documents', ['operation_id'], unique=False)
    op.create_index('ix_election_day_documents_polling_place_id', 'election_day_documents', ['polling_place_id'], unique=False)
    op.create_index('uq_election_day_documents_client_id', 'election_day_documents', ['operation_id', 'uploaded_by_user_id', 'client_generated_id'], unique=True, postgresql_where=sa.text('client_generated_id IS NOT NULL'))
    op.create_index('uq_election_day_documents_storage_key', 'election_day_documents', ['storage_key'], unique=True, postgresql_where=sa.text('storage_key IS NOT NULL'))
    op.create_table('election_day_incidents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('operation_id', sa.Uuid(), nullable=False),
    sa.Column('polling_place_id', sa.Uuid(), nullable=False),
    sa.Column('board_id', sa.Uuid(), nullable=True),
    sa.Column('reported_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='OPEN', nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('client_generated_id', sa.Uuid(), nullable=True),
    sa.Column('offline_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('PERSONNEL','ACCESS','LOGISTICS','DOCUMENTATION','CONNECTIVITY','OTHER')", name=op.f('ck_election_day_incidents_category')),
    sa.CheckConstraint("status IN ('OPEN','IN_REVIEW','RESOLVED')", name=op.f('ck_election_day_incidents_status')),
    sa.ForeignKeyConstraint(['board_id'], ['electoral_boards.id'], name=op.f('fk_election_day_incidents_board_id_electoral_boards'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['operation_id'], ['election_day_operations.id'], name=op.f('fk_election_day_incidents_operation_id_election_day_operations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['polling_place_id'], ['polling_places.id'], name=op.f('fk_election_day_incidents_polling_place_id_polling_places'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reported_by_user_id'], ['users.id'], name=op.f('fk_election_day_incidents_reported_by_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_election_day_incidents'))
    )
    op.create_index('ix_election_day_incidents_operation_id', 'election_day_incidents', ['operation_id'], unique=False)
    op.create_index('ix_election_day_incidents_polling_place_id', 'election_day_incidents', ['polling_place_id'], unique=False)
    op.create_index('ix_election_day_incidents_status', 'election_day_incidents', ['status'], unique=False)
    op.create_index('uq_election_day_incidents_client_id', 'election_day_incidents', ['operation_id', 'reported_by_user_id', 'client_generated_id'], unique=True, postgresql_where=sa.text('client_generated_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_election_day_incidents_client_id', table_name='election_day_incidents', postgresql_where=sa.text('client_generated_id IS NOT NULL'))
    op.drop_index('ix_election_day_incidents_status', table_name='election_day_incidents')
    op.drop_index('ix_election_day_incidents_polling_place_id', table_name='election_day_incidents')
    op.drop_index('ix_election_day_incidents_operation_id', table_name='election_day_incidents')
    op.drop_table('election_day_incidents')
    op.drop_index('uq_election_day_documents_storage_key', table_name='election_day_documents', postgresql_where=sa.text('storage_key IS NOT NULL'))
    op.drop_index('uq_election_day_documents_client_id', table_name='election_day_documents', postgresql_where=sa.text('client_generated_id IS NOT NULL'))
    op.drop_index('ix_election_day_documents_polling_place_id', table_name='election_day_documents')
    op.drop_index('ix_election_day_documents_operation_id', table_name='election_day_documents')
    op.drop_index('ix_election_day_documents_board_id', table_name='election_day_documents')
    op.drop_table('election_day_documents')
    op.drop_index('ix_election_day_assignments_user_id', table_name='election_day_assignments')
    op.drop_index('ix_election_day_assignments_status', table_name='election_day_assignments')
    op.drop_index('ix_election_day_assignments_polling_place_id', table_name='election_day_assignments')
    op.drop_index('ix_election_day_assignments_operation_id', table_name='election_day_assignments')
    op.drop_index('ix_election_day_assignments_board_id', table_name='election_day_assignments')
    op.drop_table('election_day_assignments')
    op.drop_index('ix_electoral_boards_polling_place_id', table_name='electoral_boards')
    op.drop_index('ix_electoral_boards_is_active', table_name='electoral_boards')
    op.drop_table('electoral_boards')
    op.drop_index('ix_polling_places_parish_id', table_name='polling_places')
    op.drop_index('ix_polling_places_is_active', table_name='polling_places')
    op.drop_index('ix_polling_places_electoral_process_id', table_name='polling_places')
    op.drop_index('ix_polling_places_canton_id', table_name='polling_places')
    op.drop_table('polling_places')
    op.drop_index('ix_election_day_operations_status', table_name='election_day_operations')
    op.drop_index('ix_election_day_operations_electoral_process_id', table_name='election_day_operations')
    op.drop_index('ix_election_day_operations_campaign_id', table_name='election_day_operations')
    op.drop_table('election_day_operations')
    # ### end Alembic commands ###
