"""aggregated survey studies v2.3

Revision ID: 20260811_0001
Revises: 20260808_0001
"""
from alembic import op
import sqlalchemy as sa
revision="20260811_0001";down_revision="20260808_0001";branch_labels=None;depends_on=None
def upgrade():
    op.execute("ALTER TABLE report_templates DROP CONSTRAINT ck_report_templates_report_type")
    op.execute("ALTER TABLE report_templates ADD CONSTRAINT ck_report_templates_report_type CHECK (report_type IN ('CAMPAIGN_EXECUTIVE_SUMMARY','OPERATIONAL_ACTIVITY','TERRITORIAL_COVERAGE','NEEDS','COMMITMENTS','SURVEY_RESULTS','SURVEY_STUDY','ELECTORAL_HISTORY','DEMOGRAPHIC_PROFILE','DATA_QUALITY','GEOGRAPHIC_AVAILABILITY'))")
    op.create_table("survey_studies",
      sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("campaign_id",sa.Uuid(),nullable=False),sa.Column("election_process_id",sa.Uuid()),
      sa.Column("code",sa.String(80),nullable=False),sa.Column("name",sa.String(180),nullable=False),sa.Column("description",sa.Text()),
      sa.Column("study_type",sa.String(20),nullable=False),sa.Column("status",sa.String(20),nullable=False,server_default="DRAFT"),
      sa.Column("fieldwork_start_date",sa.Date(),nullable=False),sa.Column("fieldwork_end_date",sa.Date(),nullable=False),sa.Column("publication_date",sa.Date()),
      sa.Column("geography_level",sa.String(20),nullable=False),sa.Column("sample_size_total",sa.Integer(),nullable=False),sa.Column("universe_description",sa.Text(),nullable=False),
      sa.Column("sampling_method",sa.String(250),nullable=False),sa.Column("collection_method",sa.String(250),nullable=False),sa.Column("confidence_level",sa.Numeric(7,6)),sa.Column("margin_of_error",sa.Numeric(7,6)),
      sa.Column("pollster_name",sa.String(180)),sa.Column("sponsor_name",sa.String(180)),sa.Column("source_type",sa.String(40),nullable=False),sa.Column("source_url",sa.String(1000)),sa.Column("notes",sa.Text()),
      sa.Column("is_official",sa.Boolean(),nullable=False,server_default=sa.false()),sa.Column("study_series_code",sa.String(80)),sa.Column("question_code",sa.String(80),nullable=False,server_default="VOTE_INTENTION"),sa.Column("result_count_notes",sa.Text()),
      sa.Column("created_by_user_id",sa.Uuid(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),
      sa.ForeignKeyConstraint(["campaign_id"],["campaigns.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["election_process_id"],["electoral_processes.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["created_by_user_id"],["users.id"],ondelete="RESTRICT"),
      sa.UniqueConstraint("campaign_id","code",name="uq_survey_studies_campaign_code"),sa.CheckConstraint("study_type IN ('POLL','TRACKING_POLL','EXIT_POLL','OTHER')",name="study_type"),sa.CheckConstraint("status IN ('DRAFT','VALIDATED','PUBLISHED','ARCHIVED')",name="status"),sa.CheckConstraint("geography_level IN ('CANTON','PARISH')",name="geography_level"),sa.CheckConstraint("sample_size_total > 0",name="sample_size_positive"),sa.CheckConstraint("fieldwork_start_date <= fieldwork_end_date",name="fieldwork_dates"),sa.CheckConstraint("confidence_level IS NULL OR confidence_level BETWEEN 0 AND 1",name="confidence_level_range"),sa.CheckConstraint("margin_of_error IS NULL OR margin_of_error BETWEEN 0 AND 1",name="margin_of_error_range"))
    op.create_index("ix_survey_studies_campaign_status","survey_studies",["campaign_id","status"]);op.create_index("ix_survey_studies_series","survey_studies",["campaign_id","study_series_code"])
    op.create_table("survey_study_territories",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("study_id",sa.Uuid(),nullable=False),sa.Column("parish_id",sa.Integer()),sa.Column("sample_size",sa.Integer(),nullable=False),sa.Column("margin_of_error",sa.Numeric(7,6)),sa.Column("coverage_notes",sa.Text()),sa.ForeignKeyConstraint(["study_id"],["survey_studies.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["parish_id"],["parishes.id"],ondelete="RESTRICT"),sa.UniqueConstraint("study_id","parish_id",name="uq_survey_study_territories_study_parish"),sa.CheckConstraint("sample_size > 0",name="sample_size_positive"),sa.CheckConstraint("margin_of_error IS NULL OR margin_of_error BETWEEN 0 AND 1",name="margin_of_error_range"));op.create_index("ix_survey_study_territories_study","survey_study_territories",["study_id"])
    op.create_table("survey_study_options",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("study_id",sa.Uuid(),nullable=False),sa.Column("code",sa.String(80),nullable=False),sa.Column("label",sa.String(180),nullable=False),sa.Column("option_type",sa.String(20),nullable=False),sa.Column("display_order",sa.Integer(),nullable=False,server_default="0"),sa.ForeignKeyConstraint(["study_id"],["survey_studies.id"],ondelete="CASCADE"),sa.UniqueConstraint("study_id","code",name="uq_survey_study_options_study_code"),sa.CheckConstraint("option_type IN ('CANDIDATE','UNDECIDED','BLANK','NULL_VOTE','OTHER','NO_RESPONSE')",name="option_type"),sa.CheckConstraint("display_order >= 0",name="display_order"))
    op.create_table("survey_study_results",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("study_id",sa.Uuid(),nullable=False),sa.Column("study_territory_id",sa.Uuid(),nullable=False),sa.Column("option_id",sa.Uuid(),nullable=False),sa.Column("response_count",sa.Integer()),sa.Column("percentage",sa.Numeric(9,8),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.ForeignKeyConstraint(["study_id"],["survey_studies.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["study_territory_id"],["survey_study_territories.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["option_id"],["survey_study_options.id"],ondelete="CASCADE"),sa.UniqueConstraint("study_id","study_territory_id","option_id",name="uq_survey_study_results_key"),sa.CheckConstraint("percentage BETWEEN 0 AND 1",name="percentage_range"),sa.CheckConstraint("response_count IS NULL OR response_count >= 0",name="response_count_nonnegative"));op.create_index("ix_survey_study_results_study","survey_study_results",["study_id"])
def downgrade():
    op.drop_table("survey_study_results");op.drop_table("survey_study_options");op.drop_table("survey_study_territories");op.drop_table("survey_studies")
    op.execute("ALTER TABLE report_templates DROP CONSTRAINT ck_report_templates_report_type")
    op.execute("ALTER TABLE report_templates ADD CONSTRAINT ck_report_templates_report_type CHECK (report_type IN ('CAMPAIGN_EXECUTIVE_SUMMARY','OPERATIONAL_ACTIVITY','TERRITORIAL_COVERAGE','NEEDS','COMMITMENTS','SURVEY_RESULTS','ELECTORAL_HISTORY','DEMOGRAPHIC_PROFILE','DATA_QUALITY','GEOGRAPHIC_AVAILABILITY'))")
