"""campaigns candidates territory

Revision ID: 49422095ee46
Revises: 20260803_0001
Create Date: 2026-08-03 15:05:59.395195
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.db.spatial import SpatialGeometry


revision: str = '49422095ee46'
down_revision: Union[str, None] = '20260803_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provinces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provinces'))
    )
    op.create_index('ix_provinces_code', 'provinces', ['code'], unique=True)
    op.create_index('ix_provinces_name', 'provinces', ['name'], unique=True)
    op.create_table('cantons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('province_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('dpa_code', sa.String(length=4), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('geometry', SpatialGeometry('MULTIPOLYGON'), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['province_id'], ['provinces.id'], name=op.f('fk_cantons_province_id_provinces'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cantons')),
    sa.UniqueConstraint('province_id', 'code', name='uq_cantons_province_code'),
    sa.UniqueConstraint('province_id', 'name', name='uq_cantons_province_name')
    )
    op.create_index('ix_cantons_dpa_code', 'cantons', ['dpa_code'], unique=True)
    op.create_index('ix_cantons_province_id', 'cantons', ['province_id'], unique=False)
    op.create_index('ix_cantons_geometry_gist', 'cantons', ['geometry'], unique=False, postgresql_using='gist')
    op.create_table('campaigns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('canton_id', sa.Integer(), nullable=False),
    sa.Column('office_type', sa.String(length=30), nullable=False),
    sa.Column('election_name', sa.String(length=180), nullable=False),
    sa.Column('election_date', sa.Date(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("office_type IN ('MAYOR','URBAN_COUNCILOR','RURAL_COUNCILOR','PARISH_BOARD')", name=op.f('ck_campaigns_office_type')),
    sa.CheckConstraint("status IN ('DRAFT','ACTIVE','COMPLETED','ARCHIVED')", name=op.f('ck_campaigns_status')),
    sa.CheckConstraint('start_date IS NULL OR election_date >= start_date', name=op.f('ck_campaigns_election_after_start')),
    sa.CheckConstraint('start_date IS NULL OR end_date IS NULL OR start_date <= end_date', name=op.f('ck_campaigns_date_range')),
    sa.ForeignKeyConstraint(['canton_id'], ['cantons.id'], name=op.f('fk_campaigns_canton_id_cantons'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_campaigns_created_by_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaigns'))
    )
    op.create_index('ix_campaigns_canton_id', 'campaigns', ['canton_id'], unique=False)
    op.create_index('ix_campaigns_slug', 'campaigns', ['slug'], unique=True)
    op.create_table('parishes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canton_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('dpa_code', sa.String(length=6), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parish_type', sa.String(length=10), nullable=False),
    sa.Column('geometry', SpatialGeometry('MULTIPOLYGON'), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("parish_type IN ('URBAN','RURAL')", name=op.f('ck_parishes_parish_type')),
    sa.ForeignKeyConstraint(['canton_id'], ['cantons.id'], name=op.f('fk_parishes_canton_id_cantons'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parishes')),
    sa.UniqueConstraint('canton_id', 'code', name='uq_parishes_canton_code'),
    sa.UniqueConstraint('canton_id', 'name', name='uq_parishes_canton_name')
    )
    op.create_index('ix_parishes_canton_id', 'parishes', ['canton_id'], unique=False)
    op.create_index('ix_parishes_dpa_code', 'parishes', ['dpa_code'], unique=True)
    op.create_index('ix_parishes_geometry_gist', 'parishes', ['geometry'], unique=False, postgresql_using='gist')
    op.create_table('campaign_users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('assigned_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.id'], name=op.f('fk_campaign_users_assigned_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_campaign_users_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_campaign_users_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaign_users')),
    sa.UniqueConstraint('campaign_id', 'user_id', name='uq_campaign_users_campaign_user')
    )
    op.create_index('ix_campaign_users_campaign_id', 'campaign_users', ['campaign_id'], unique=False)
    op.create_index('ix_campaign_users_user_id', 'campaign_users', ['user_id'], unique=False)
    op.create_table('candidates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=180), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('political_organization', sa.String(length=180), nullable=True),
    sa.Column('list_number', sa.Integer(), nullable=True),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('birth_date IS NULL OR birth_date <= CURRENT_DATE', name=op.f('ck_candidates_birth_not_future')),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_candidates_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_candidates_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidates'))
    )
    op.create_index('ix_candidates_campaign_id', 'candidates', ['campaign_id'], unique=True)
    op.create_index('ix_candidates_user_id', 'candidates', ['user_id'], unique=True)
    op.create_table('communities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('parish_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location', SpatialGeometry('POINT'), nullable=True),
    sa.Column('is_official', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('latitude IS NULL OR latitude BETWEEN -90 AND 90', name=op.f('ck_communities_latitude_range')),
    sa.CheckConstraint('longitude IS NULL OR longitude BETWEEN -180 AND 180', name=op.f('ck_communities_longitude_range')),
    sa.ForeignKeyConstraint(['parish_id'], ['parishes.id'], name=op.f('fk_communities_parish_id_parishes'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_communities')),
    sa.UniqueConstraint('parish_id', 'name', name='uq_communities_parish_name')
    )
    op.create_index('ix_communities_parish_id', 'communities', ['parish_id'], unique=False)
    op.create_index('ix_communities_location_gist', 'communities', ['location'], unique=False, postgresql_using='gist')
    op.create_index('uq_communities_parish_lower_name', 'communities', ['parish_id', sa.text('lower(name)')], unique=True)
    op.create_table('sectors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('community_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location', SpatialGeometry('POINT'), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('latitude IS NULL OR latitude BETWEEN -90 AND 90', name=op.f('ck_sectors_latitude_range')),
    sa.CheckConstraint('longitude IS NULL OR longitude BETWEEN -180 AND 180', name=op.f('ck_sectors_longitude_range')),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], name=op.f('fk_sectors_community_id_communities'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sectors')),
    sa.UniqueConstraint('community_id', 'name', name='uq_sectors_community_name')
    )
    op.create_index('ix_sectors_community_id', 'sectors', ['community_id'], unique=False)
    op.create_index('ix_sectors_location_gist', 'sectors', ['location'], unique=False, postgresql_using='gist')
    op.create_index('uq_sectors_community_lower_name', 'sectors', ['community_id', sa.text('lower(name)')], unique=True)
    op.create_table('territorial_assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('parish_id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Uuid(), nullable=True),
    sa.Column('sector_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('assigned_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('sector_id IS NULL OR community_id IS NOT NULL', name=op.f('ck_territorial_assignments_sector_requires_community')),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.id'], name=op.f('fk_territorial_assignments_assigned_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_territorial_assignments_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], name=op.f('fk_territorial_assignments_community_id_communities'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parish_id'], ['parishes.id'], name=op.f('fk_territorial_assignments_parish_id_parishes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], name=op.f('fk_territorial_assignments_sector_id_sectors'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_territorial_assignments_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_territorial_assignments')),
    sa.UniqueConstraint('campaign_id', 'user_id', 'parish_id', 'community_id', 'sector_id', name='uq_territorial_assignment_scope')
    )
    op.create_index('ix_territorial_assignments_campaign_id', 'territorial_assignments', ['campaign_id'], unique=False)
    op.create_index('ix_territorial_assignments_parish_id', 'territorial_assignments', ['parish_id'], unique=False)
    op.create_index('ix_territorial_assignments_user_id', 'territorial_assignments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_territorial_assignments_user_id', table_name='territorial_assignments')
    op.drop_index('ix_territorial_assignments_parish_id', table_name='territorial_assignments')
    op.drop_index('ix_territorial_assignments_campaign_id', table_name='territorial_assignments')
    op.drop_table('territorial_assignments')
    op.drop_index('uq_sectors_community_lower_name', table_name='sectors')
    op.drop_index('ix_sectors_location_gist', table_name='sectors', postgresql_using='gist')
    op.drop_index('ix_sectors_community_id', table_name='sectors')
    op.drop_table('sectors')
    op.drop_index('uq_communities_parish_lower_name', table_name='communities')
    op.drop_index('ix_communities_location_gist', table_name='communities', postgresql_using='gist')
    op.drop_index('ix_communities_parish_id', table_name='communities')
    op.drop_table('communities')
    op.drop_index('ix_candidates_user_id', table_name='candidates')
    op.drop_index('ix_candidates_campaign_id', table_name='candidates')
    op.drop_table('candidates')
    op.drop_index('ix_campaign_users_user_id', table_name='campaign_users')
    op.drop_index('ix_campaign_users_campaign_id', table_name='campaign_users')
    op.drop_table('campaign_users')
    op.drop_index('ix_parishes_geometry_gist', table_name='parishes', postgresql_using='gist')
    op.drop_index('ix_parishes_dpa_code', table_name='parishes')
    op.drop_index('ix_parishes_canton_id', table_name='parishes')
    op.drop_table('parishes')
    op.drop_index('ix_campaigns_slug', table_name='campaigns')
    op.drop_index('ix_campaigns_canton_id', table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index('ix_cantons_geometry_gist', table_name='cantons', postgresql_using='gist')
    op.drop_index('ix_cantons_province_id', table_name='cantons')
    op.drop_index('ix_cantons_dpa_code', table_name='cantons')
    op.drop_table('cantons')
    op.drop_index('ix_provinces_name', table_name='provinces')
    op.drop_index('ix_provinces_code', table_name='provinces')
    op.drop_table('provinces')
    # ### end Alembic commands ###

