"""reports and explainable operational alerts

Revision ID: 88caa938c6b8
Revises: 12cff41d3836
Create Date: 2026-08-03 18:45:44.100927
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '88caa938c6b8'
down_revision: Union[str, None] = '12cff41d3836'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('module', sa.String(length=30), nullable=False),
    sa.Column('condition_type', sa.String(length=80), nullable=False),
    sa.Column('default_severity', sa.String(length=20), nullable=False),
    sa.Column('configuration', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_system', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("default_severity IN ('INFO','WARNING','CRITICAL')", name=op.f('ck_alert_rules_severity')),
    sa.CheckConstraint("module IN ('OPERATIONS','COMMITMENTS','SURVEYS','DATA_IMPORTS','ELECTORAL_DATA','DEMOGRAPHICS','GEOMETRY','DATA_QUALITY')", name=op.f('ck_alert_rules_module')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_alert_rules_created_by_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_rules'))
    )
    op.create_index('ix_alert_rules_code', 'alert_rules', ['code'], unique=True)
    op.create_index('ix_alert_rules_condition_type', 'alert_rules', ['condition_type'], unique=False)
    op.create_index('ix_alert_rules_is_active', 'alert_rules', ['is_active'], unique=False)
    op.create_index('ix_alert_rules_module', 'alert_rules', ['module'], unique=False)
    op.create_table('report_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('allowed_formats', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('definition', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_system', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("report_type IN ('CAMPAIGN_EXECUTIVE_SUMMARY','OPERATIONAL_ACTIVITY','TERRITORIAL_COVERAGE','NEEDS','COMMITMENTS','SURVEY_RESULTS','ELECTORAL_HISTORY','DEMOGRAPHIC_PROFILE','DATA_QUALITY','GEOGRAPHIC_AVAILABILITY')", name=op.f('ck_report_templates_report_type')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_report_templates_created_by_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_templates'))
    )
    op.create_index('ix_report_templates_code', 'report_templates', ['code'], unique=True)
    op.create_index('ix_report_templates_is_active', 'report_templates', ['is_active'], unique=False)
    op.create_index('ix_report_templates_report_type', 'report_templates', ['report_type'], unique=False)
    op.create_table('report_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('report_template_id', sa.Uuid(), nullable=False),
    sa.Column('requested_format', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=True),
    sa.Column('date_to', sa.Date(), nullable=True),
    sa.Column('filters', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('resolved_scope', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('title', sa.String(length=220), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('requested_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("requested_format IN ('PDF','XLSX')", name=op.f('ck_report_runs_requested_format')),
    sa.CheckConstraint("status IN ('PENDING','GENERATING','COMPLETED','FAILED','CANCELLED')", name=op.f('ck_report_runs_status')),
    sa.CheckConstraint('date_from IS NULL OR date_to IS NULL OR date_from <= date_to', name=op.f('ck_report_runs_date_range')),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_report_runs_campaign_id_campaigns'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['report_template_id'], ['report_templates.id'], name=op.f('fk_report_runs_report_template_id_report_templates'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], name=op.f('fk_report_runs_requested_by_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_runs'))
    )
    op.create_index('ix_report_runs_campaign_id', 'report_runs', ['campaign_id'], unique=False)
    op.create_index('ix_report_runs_campaign_report_date', 'report_runs', ['campaign_id', 'report_date'], unique=False)
    op.create_index('ix_report_runs_report_date', 'report_runs', ['report_date'], unique=False)
    op.create_index('ix_report_runs_report_template_id', 'report_runs', ['report_template_id'], unique=False)
    op.create_index('ix_report_runs_requested_by_user_id', 'report_runs', ['requested_by_user_id'], unique=False)
    op.create_index('ix_report_runs_status', 'report_runs', ['status'], unique=False)
    op.create_table('report_artifacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('report_run_id', sa.Uuid(), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('original_download_name', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('expires_on', sa.Date(), nullable=False),
    sa.Column('is_available', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("format IN ('PDF','XLSX')", name=op.f('ck_report_artifacts_format')),
    sa.CheckConstraint('size_bytes >= 0', name=op.f('ck_report_artifacts_size_nonnegative')),
    sa.ForeignKeyConstraint(['report_run_id'], ['report_runs.id'], name=op.f('fk_report_artifacts_report_run_id_report_runs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_artifacts'))
    )
    op.create_index('ix_report_artifacts_expires_on', 'report_artifacts', ['expires_on'], unique=False)
    op.create_index('ix_report_artifacts_is_available', 'report_artifacts', ['is_available'], unique=False)
    op.create_index('ix_report_artifacts_report_run_id', 'report_artifacts', ['report_run_id'], unique=True)
    op.create_index('ix_report_artifacts_storage_key', 'report_artifacts', ['storage_key'], unique=True)
    op.create_table('operational_alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('alert_rule_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=220), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('detected_date', sa.Date(), nullable=False),
    sa.Column('last_seen_date', sa.Date(), nullable=False),
    sa.Column('resolved_date', sa.Date(), nullable=True),
    sa.Column('parish_id', sa.Integer(), nullable=True),
    sa.Column('community_id', sa.Uuid(), nullable=True),
    sa.Column('sector_id', sa.Uuid(), nullable=True),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.Uuid(), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("severity IN ('INFO','WARNING','CRITICAL')", name=op.f('ck_operational_alerts_severity')),
    sa.CheckConstraint("status IN ('OPEN','ACKNOWLEDGED','RESOLVED','DISMISSED')", name=op.f('ck_operational_alerts_status')),
    sa.ForeignKeyConstraint(['alert_rule_id'], ['alert_rules.id'], name=op.f('fk_operational_alerts_alert_rule_id_alert_rules'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_operational_alerts_campaign_id_campaigns'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], name=op.f('fk_operational_alerts_community_id_communities'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parish_id'], ['parishes.id'], name=op.f('fk_operational_alerts_parish_id_parishes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], name=op.f('fk_operational_alerts_sector_id_sectors'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operational_alerts'))
    )
    op.create_index('ix_operational_alerts_alert_rule_id', 'operational_alerts', ['alert_rule_id'], unique=False)
    op.create_index('ix_operational_alerts_campaign_id', 'operational_alerts', ['campaign_id'], unique=False)
    op.create_index('ix_operational_alerts_campaign_severity', 'operational_alerts', ['campaign_id', 'severity'], unique=False)
    op.create_index('ix_operational_alerts_campaign_status', 'operational_alerts', ['campaign_id', 'status'], unique=False)
    op.create_index('ix_operational_alerts_detected_date', 'operational_alerts', ['detected_date'], unique=False)
    op.create_index('ix_operational_alerts_parish_id', 'operational_alerts', ['parish_id'], unique=False)
    op.create_index('ix_operational_alerts_resource', 'operational_alerts', ['resource_type', 'resource_id'], unique=False)
    op.create_index('ix_operational_alerts_severity', 'operational_alerts', ['severity'], unique=False)
    op.create_index('ix_operational_alerts_status', 'operational_alerts', ['status'], unique=False)
    op.create_index('uq_operational_alerts_campaign_fingerprint', 'operational_alerts', ['campaign_id', 'fingerprint'], unique=True)
    op.create_table('alert_acknowledgements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('alert_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('action_date', sa.Date(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('performed_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action IN ('ACKNOWLEDGE','RESOLVE','DISMISS','REOPEN')", name=op.f('ck_alert_acknowledgements_action')),
    sa.ForeignKeyConstraint(['alert_id'], ['operational_alerts.id'], name=op.f('fk_alert_acknowledgements_alert_id_operational_alerts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['performed_by_user_id'], ['users.id'], name=op.f('fk_alert_acknowledgements_performed_by_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_acknowledgements'))
    )
    op.create_index('ix_alert_acknowledgements_action', 'alert_acknowledgements', ['action'], unique=False)
    op.create_index('ix_alert_acknowledgements_action_date', 'alert_acknowledgements', ['action_date'], unique=False)
    op.create_index('ix_alert_acknowledgements_alert_id', 'alert_acknowledgements', ['alert_id'], unique=False)
    op.create_index('ix_alert_acknowledgements_performed_by_user_id', 'alert_acknowledgements', ['performed_by_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alert_acknowledgements_performed_by_user_id', table_name='alert_acknowledgements')
    op.drop_index('ix_alert_acknowledgements_alert_id', table_name='alert_acknowledgements')
    op.drop_index('ix_alert_acknowledgements_action_date', table_name='alert_acknowledgements')
    op.drop_index('ix_alert_acknowledgements_action', table_name='alert_acknowledgements')
    op.drop_table('alert_acknowledgements')
    op.drop_index('uq_operational_alerts_campaign_fingerprint', table_name='operational_alerts')
    op.drop_index('ix_operational_alerts_status', table_name='operational_alerts')
    op.drop_index('ix_operational_alerts_severity', table_name='operational_alerts')
    op.drop_index('ix_operational_alerts_resource', table_name='operational_alerts')
    op.drop_index('ix_operational_alerts_parish_id', table_name='operational_alerts')
    op.drop_index('ix_operational_alerts_detected_date', table_name='operational_alerts')
    op.drop_index('ix_operational_alerts_campaign_status', table_name='operational_alerts')
    op.drop_index('ix_operational_alerts_campaign_severity', table_name='operational_alerts')
    op.drop_index('ix_operational_alerts_campaign_id', table_name='operational_alerts')
    op.drop_index('ix_operational_alerts_alert_rule_id', table_name='operational_alerts')
    op.drop_table('operational_alerts')
    op.drop_index('ix_report_artifacts_storage_key', table_name='report_artifacts')
    op.drop_index('ix_report_artifacts_report_run_id', table_name='report_artifacts')
    op.drop_index('ix_report_artifacts_is_available', table_name='report_artifacts')
    op.drop_index('ix_report_artifacts_expires_on', table_name='report_artifacts')
    op.drop_table('report_artifacts')
    op.drop_index('ix_report_runs_status', table_name='report_runs')
    op.drop_index('ix_report_runs_requested_by_user_id', table_name='report_runs')
    op.drop_index('ix_report_runs_report_template_id', table_name='report_runs')
    op.drop_index('ix_report_runs_report_date', table_name='report_runs')
    op.drop_index('ix_report_runs_campaign_report_date', table_name='report_runs')
    op.drop_index('ix_report_runs_campaign_id', table_name='report_runs')
    op.drop_table('report_runs')
    op.drop_index('ix_report_templates_report_type', table_name='report_templates')
    op.drop_index('ix_report_templates_is_active', table_name='report_templates')
    op.drop_index('ix_report_templates_code', table_name='report_templates')
    op.drop_table('report_templates')
    op.drop_index('ix_alert_rules_module', table_name='alert_rules')
    op.drop_index('ix_alert_rules_is_active', table_name='alert_rules')
    op.drop_index('ix_alert_rules_condition_type', table_name='alert_rules')
    op.drop_index('ix_alert_rules_code', table_name='alert_rules')
    op.drop_table('alert_rules')
    # ### end Alembic commands ###

