"""operational activities needs commitments

Revision ID: d00e4cd30f04
Revises: 49422095ee46
Create Date: 2026-08-03 15:48:56.587805
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.db.spatial import SpatialGeometry


revision: str = 'd00e4cd30f04'
down_revision: Union[str, None] = '49422095ee46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_types'))
    )
    op.create_index('ix_activity_types_code', 'activity_types', ['code'], unique=True)
    op.create_index('ix_activity_types_name', 'activity_types', ['name'], unique=True)
    op.create_table('need_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_need_categories'))
    )
    op.create_index('ix_need_categories_code', 'need_categories', ['code'], unique=True)
    op.create_index('ix_need_categories_name', 'need_categories', ['name'], unique=True)
    op.create_table('territorial_activities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('activity_type_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('parish_id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Uuid(), nullable=True),
    sa.Column('sector_id', sa.Uuid(), nullable=True),
    sa.Column('location_name', sa.String(length=180), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location', SpatialGeometry('POINT'), nullable=True),
    sa.Column('responsible_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PLANNED','COMPLETED','CANCELLED')", name=op.f('ck_territorial_activities_status')),
    sa.CheckConstraint('latitude IS NULL OR latitude BETWEEN -90 AND 90', name=op.f('ck_territorial_activities_latitude_range')),
    sa.CheckConstraint('longitude IS NULL OR longitude BETWEEN -180 AND 180', name=op.f('ck_territorial_activities_longitude_range')),
    sa.CheckConstraint('sector_id IS NULL OR community_id IS NOT NULL', name=op.f('ck_territorial_activities_sector_requires_community')),
    sa.ForeignKeyConstraint(['activity_type_id'], ['activity_types.id'], name=op.f('fk_territorial_activities_activity_type_id_activity_types'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_territorial_activities_campaign_id_campaigns'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], name=op.f('fk_territorial_activities_community_id_communities'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_territorial_activities_created_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parish_id'], ['parishes.id'], name=op.f('fk_territorial_activities_parish_id_parishes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['responsible_user_id'], ['users.id'], name=op.f('fk_territorial_activities_responsible_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], name=op.f('fk_territorial_activities_sector_id_sectors'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_territorial_activities'))
    )
    op.create_index('ix_territorial_activities_activity_date', 'territorial_activities', ['activity_date'], unique=False)
    op.create_index('ix_territorial_activities_campaign_date', 'territorial_activities', ['campaign_id', 'activity_date'], unique=False)
    op.create_index('ix_territorial_activities_campaign_id', 'territorial_activities', ['campaign_id'], unique=False)
    op.create_index('ix_territorial_activities_campaign_parish', 'territorial_activities', ['campaign_id', 'parish_id'], unique=False)
    op.create_index('ix_territorial_activities_community_id', 'territorial_activities', ['community_id'], unique=False)
    op.create_index('ix_territorial_activities_location_gist', 'territorial_activities', ['location'], unique=False, postgresql_using='gist')
    op.create_index('ix_territorial_activities_parish_id', 'territorial_activities', ['parish_id'], unique=False)
    op.create_index('ix_territorial_activities_responsible_user_id', 'territorial_activities', ['responsible_user_id'], unique=False)
    op.create_index('ix_territorial_activities_sector_id', 'territorial_activities', ['sector_id'], unique=False)
    op.create_index('ix_territorial_activities_status', 'territorial_activities', ['status'], unique=False)
    op.create_table('activity_evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('activity_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('evidence_date', sa.Date(), nullable=True),
    sa.Column('uploaded_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("evidence_type IN ('PHOTO','VIDEO','DOCUMENT','NEWS_LINK','SOCIAL_LINK','OTHER')", name=op.f('ck_activity_evidence_evidence_type')),
    sa.ForeignKeyConstraint(['activity_id'], ['territorial_activities.id'], name=op.f('fk_activity_evidence_activity_id_territorial_activities'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], name=op.f('fk_activity_evidence_uploaded_by_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_evidence'))
    )
    op.create_index('ix_activity_evidence_activity_id', 'activity_evidence', ['activity_id'], unique=False)
    op.create_index('ix_activity_evidence_evidence_type', 'activity_evidence', ['evidence_type'], unique=False)
    op.create_index('ix_activity_evidence_is_active', 'activity_evidence', ['is_active'], unique=False)
    op.create_table('activity_participant_summaries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('activity_id', sa.Uuid(), nullable=False),
    sa.Column('estimated_attendees', sa.Integer(), server_default='0', nullable=False),
    sa.Column('organizations_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('community_leaders_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('campaign_team_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('estimated_attendees>=0 AND organizations_count>=0 AND community_leaders_count>=0 AND campaign_team_count>=0', name=op.f('ck_activity_participant_summaries_nonnegative_counts')),
    sa.ForeignKeyConstraint(['activity_id'], ['territorial_activities.id'], name=op.f('fk_activity_participant_summaries_activity_id_territorial_activities'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_activity_participant_summaries_created_by_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_participant_summaries'))
    )
    op.create_index('ix_participant_summaries_activity_id', 'activity_participant_summaries', ['activity_id'], unique=True)
    op.create_table('citizen_needs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('activity_id', sa.Uuid(), nullable=False),
    sa.Column('need_category_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('mentions_count', sa.Integer(), server_default='1', nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('parish_id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Uuid(), nullable=True),
    sa.Column('sector_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("priority IN ('LOW','MEDIUM','HIGH','CRITICAL')", name=op.f('ck_citizen_needs_priority')),
    sa.CheckConstraint("status IN ('IDENTIFIED','UNDER_REVIEW','INCLUDED_IN_PLAN','DISCARDED')", name=op.f('ck_citizen_needs_status')),
    sa.CheckConstraint('mentions_count>=1', name=op.f('ck_citizen_needs_mentions_positive')),
    sa.ForeignKeyConstraint(['activity_id'], ['territorial_activities.id'], name=op.f('fk_citizen_needs_activity_id_territorial_activities'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_citizen_needs_campaign_id_campaigns'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], name=op.f('fk_citizen_needs_community_id_communities'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_citizen_needs_created_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['need_category_id'], ['need_categories.id'], name=op.f('fk_citizen_needs_need_category_id_need_categories'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parish_id'], ['parishes.id'], name=op.f('fk_citizen_needs_parish_id_parishes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], name=op.f('fk_citizen_needs_sector_id_sectors'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_citizen_needs')),
    sa.UniqueConstraint('activity_id', 'need_category_id', 'title', name='uq_citizen_needs_activity_category_title')
    )
    op.create_index('ix_citizen_needs_activity_id', 'citizen_needs', ['activity_id'], unique=False)
    op.create_index('ix_citizen_needs_campaign_category', 'citizen_needs', ['campaign_id', 'need_category_id'], unique=False)
    op.create_index('ix_citizen_needs_campaign_id', 'citizen_needs', ['campaign_id'], unique=False)
    op.create_index('ix_citizen_needs_campaign_parish', 'citizen_needs', ['campaign_id', 'parish_id'], unique=False)
    op.create_index('ix_citizen_needs_need_category_id', 'citizen_needs', ['need_category_id'], unique=False)
    op.create_index('ix_citizen_needs_parish_id', 'citizen_needs', ['parish_id'], unique=False)
    op.create_index('ix_citizen_needs_priority', 'citizen_needs', ['priority'], unique=False)
    op.create_index('ix_citizen_needs_status', 'citizen_needs', ['status'], unique=False)
    op.create_table('commitments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('activity_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('responsible_user_id', sa.Uuid(), nullable=True),
    sa.Column('parish_id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Uuid(), nullable=True),
    sa.Column('sector_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("priority IN ('LOW','MEDIUM','HIGH','CRITICAL')", name=op.f('ck_commitments_priority')),
    sa.CheckConstraint("status IN ('PENDING','IN_PROGRESS','COMPLETED','CANCELLED')", name=op.f('ck_commitments_status')),
    sa.CheckConstraint("status='COMPLETED' OR completed_date IS NULL", name=op.f('ck_commitments_completed_date_status')),
    sa.ForeignKeyConstraint(['activity_id'], ['territorial_activities.id'], name=op.f('fk_commitments_activity_id_territorial_activities'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_commitments_campaign_id_campaigns'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], name=op.f('fk_commitments_community_id_communities'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_commitments_created_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parish_id'], ['parishes.id'], name=op.f('fk_commitments_parish_id_parishes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['responsible_user_id'], ['users.id'], name=op.f('fk_commitments_responsible_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], name=op.f('fk_commitments_sector_id_sectors'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_commitments'))
    )
    op.create_index('ix_commitments_campaign_due_date', 'commitments', ['campaign_id', 'due_date'], unique=False)
    op.create_index('ix_commitments_campaign_id', 'commitments', ['campaign_id'], unique=False)
    op.create_index('ix_commitments_campaign_status', 'commitments', ['campaign_id', 'status'], unique=False)
    op.create_index('ix_commitments_due_date', 'commitments', ['due_date'], unique=False)
    op.create_index('ix_commitments_parish_id', 'commitments', ['parish_id'], unique=False)
    op.create_index('ix_commitments_priority', 'commitments', ['priority'], unique=False)
    op.create_index('ix_commitments_responsible_user_id', 'commitments', ['responsible_user_id'], unique=False)
    op.create_index('ix_commitments_status', 'commitments', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_commitments_status', table_name='commitments')
    op.drop_index('ix_commitments_responsible_user_id', table_name='commitments')
    op.drop_index('ix_commitments_priority', table_name='commitments')
    op.drop_index('ix_commitments_parish_id', table_name='commitments')
    op.drop_index('ix_commitments_due_date', table_name='commitments')
    op.drop_index('ix_commitments_campaign_status', table_name='commitments')
    op.drop_index('ix_commitments_campaign_id', table_name='commitments')
    op.drop_index('ix_commitments_campaign_due_date', table_name='commitments')
    op.drop_table('commitments')
    op.drop_index('ix_citizen_needs_status', table_name='citizen_needs')
    op.drop_index('ix_citizen_needs_priority', table_name='citizen_needs')
    op.drop_index('ix_citizen_needs_parish_id', table_name='citizen_needs')
    op.drop_index('ix_citizen_needs_need_category_id', table_name='citizen_needs')
    op.drop_index('ix_citizen_needs_campaign_parish', table_name='citizen_needs')
    op.drop_index('ix_citizen_needs_campaign_id', table_name='citizen_needs')
    op.drop_index('ix_citizen_needs_campaign_category', table_name='citizen_needs')
    op.drop_index('ix_citizen_needs_activity_id', table_name='citizen_needs')
    op.drop_table('citizen_needs')
    op.drop_index('ix_participant_summaries_activity_id', table_name='activity_participant_summaries')
    op.drop_table('activity_participant_summaries')
    op.drop_index('ix_activity_evidence_is_active', table_name='activity_evidence')
    op.drop_index('ix_activity_evidence_evidence_type', table_name='activity_evidence')
    op.drop_index('ix_activity_evidence_activity_id', table_name='activity_evidence')
    op.drop_table('activity_evidence')
    op.drop_index('ix_territorial_activities_status', table_name='territorial_activities')
    op.drop_index('ix_territorial_activities_sector_id', table_name='territorial_activities')
    op.drop_index('ix_territorial_activities_responsible_user_id', table_name='territorial_activities')
    op.drop_index('ix_territorial_activities_parish_id', table_name='territorial_activities')
    op.drop_index('ix_territorial_activities_location_gist', table_name='territorial_activities', postgresql_using='gist')
    op.drop_index('ix_territorial_activities_community_id', table_name='territorial_activities')
    op.drop_index('ix_territorial_activities_campaign_parish', table_name='territorial_activities')
    op.drop_index('ix_territorial_activities_campaign_id', table_name='territorial_activities')
    op.drop_index('ix_territorial_activities_campaign_date', table_name='territorial_activities')
    op.drop_index('ix_territorial_activities_activity_date', table_name='territorial_activities')
    op.drop_table('territorial_activities')
    op.drop_index('ix_need_categories_name', table_name='need_categories')
    op.drop_index('ix_need_categories_code', table_name='need_categories')
    op.drop_table('need_categories')
    op.drop_index('ix_activity_types_name', table_name='activity_types')
    op.drop_index('ix_activity_types_code', table_name='activity_types')
    op.drop_table('activity_types')
    # ### end Alembic commands ###

