export type SurveyOption = {
  id: string;
  question_id: string;
  code: string;
  label: string;
  description?: string | null;
  display_order: number;
  is_other: boolean;
  is_active: boolean;
};
export type Question = {
  id: string;
  survey_id: string;
  section_id: string;
  code: string;
  question_text: string;
  help_text?: string | null;
  question_type: string;
  is_required: boolean;
  display_order: number;
  allow_other: boolean;
  min_value?: number | null;
  max_value?: number | null;
  min_length?: number | null;
  max_length?: number | null;
  min_selections?: number | null;
  max_selections?: number | null;
  rating_min?: number | null;
  rating_max?: number | null;
  rating_min_label?: string | null;
  rating_max_label?: string | null;
  is_active: boolean;
  options: SurveyOption[];
};
export type Section = {
  id: string;
  survey_id: string;
  title: string;
  description?: string | null;
  display_order: number;
  is_active: boolean;
  questions: Question[];
};
export type Survey = {
  id: string;
  campaign_id: string;
  title: string;
  slug: string;
  description?: string | null;
  instructions?: string | null;
  status: string;
  start_date?: string | null;
  end_date?: string | null;
  target_scope: string;
  published_date?: string | null;
  closed_date?: string | null;
  allow_multiple_submissions: boolean;
  anonymous_only: boolean;
  show_progress: boolean;
  thank_you_message?: string | null;
  is_active: boolean;
  sections?: Section[];
  total_valid_responses?: number;
};
export type SurveyPage = {
  items: Survey[];
  page: number;
  page_size: number;
  total: number;
  total_pages: number;
};
export type QuestionResult = {
  code: string;
  question_text: string;
  question_type: string;
  answered_count: number;
  options: { code: string; label: string; count: number; percentage?: number | null }[];
  numeric?: {
    count: number;
    average?: number | null;
    minimum?: number | null;
    maximum?: number | null;
    median?: number | null;
    distribution?: Record<string, number> | null;
  } | null;
  text?: { count: number; non_empty_count: number } | null;
};
export type SurveyResults = {
  survey_id: string;
  title: string;
  date_from?: string | null;
  date_to?: string | null;
  total_responses: number;
  valid_responses: number;
  invalid_responses: number;
  complete_responses: number;
  responses_by_parish: Record<string, unknown>[];
  responses_by_channel: Record<string, unknown>[];
  responses_by_age_range: Record<string, unknown>[];
  question_results: QuestionResult[];
};
