from datetime import date
from app.reports.common import format_integer_es_ec


QUALITY = {"HIGH": "Alta", "MEDIUM": "Media", "LOW": "Baja", "INSUFFICIENT_DATA": "Datos insuficientes"}
WARNING = ("Esta es una estimación estadística agregada de participación electoral. No constituye predicción de resultados por candidato, intención de voto ni probabilidad de victoria. "
           "Los valores constituyen escenarios analíticos y no una garantía de participación efectiva.")
UNIVERSE = ("El universo utilizado por el modelo corresponde a las personas habilitadas para sufragar según el Registro Electoral del Consejo Nacional Electoral. "
            "La proyección no se calcula sobre la población total censada por el INEC. La versión V1 no aplica tasas diferenciadas de participación por grupo etario. "
            "Los grupos con voto facultativo forman parte del universo únicamente cuando constan habilitados en el Registro Electoral.")


def build_current_election_sections(data):
    current, history, projection, parishes = data["snapshot"], data["historical"], data["projection"], data["parishes"]
    context, total = data.get("report_context", {}), current["registered_voters"]
    h19, h23 = history.get("2019", {}), history.get("2023", {})
    def change(a, b): return b - a, (b - a) / a if a else None
    r19, r23 = h19.get("registered_voters"), h23.get("registered_voters")
    cover = {**context, "snapshot_date": current["snapshot_date"], "model_code": projection["model_code"], "model_version": projection["model_version"]}
    summary = {"title": "Resumen", "context": cover, "subtitle": "REGISTRO ELECTORAL ACTUAL · OBSERVADO · CNE",
        "text": f"Elección actual. El escenario central estima aproximadamente {format_integer_es_ec(projection['expected_voters_central'])} participantes, dentro de un rango de {format_integer_es_ec(projection['expected_voters_low'])} a {format_integer_es_ec(projection['expected_voters_high'])} según los escenarios bajo y alto.",
        "headers": ["Indicador", "Valor", "Proporción"], "formats": [None, "integer", "percent"],
        "rows": [["Electores", total, None], ["Hombres", current["male_voters"], current["male_voters"] / total], ["Mujeres", current["female_voters"], current["female_voters"] / total], ["Juntas", current["juntas"], None], ["Corte", date.fromisoformat(str(current["snapshot_date"])), None]]}
    historical = {"title": "Participación histórica", "subtitle": "OBSERVADO · CNE", "headers": ["Proceso", "Electores", "Sufragantes", "Participación"], "formats": [None, "integer", "integer", "percent"], "rows": [[y, history.get(y, {}).get("registered_voters"), history.get(y, {}).get("ballots_cast"), history.get(y, {}).get("turnout_rate")] for y in ("2019", "2023")]}
    scenarios = {"title": "Proyección principal", "subtitle": "PROYECCIÓN DE PARTICIPACIÓN · PROYECTADO · TERRITORIO ELECTORAL", "text": WARNING, "headers": ["Escenario", "Participantes", "Tasa"], "formats": [None, "integer", "percent"], "rows": [["BAJO", projection["expected_voters_low"], projection["expected_voters_low"] / total], ["CENTRAL — escenario de referencia", projection["expected_voters_central"], projection["expected_voters_central"] / total], ["ALTO", projection["expected_voters_high"], projection["expected_voters_high"] / total]]}
    parish = {"title": "Proyección parroquial", "headers": ["Parroquia", "Electores actuales", "Participación 2019", "Participación 2023", "Escenario bajo", "Escenario central", "Escenario alto", "Votantes centrales", "Calidad"], "formats": [None, "integer", "percent", "percent", "percent", "percent", "percent", "integer", None], "col_widths": [18, 12, 11, 11, 10, 11, 10, 12, 9], "font_size": 6.2, "rows": [[p["name"], p["registered_voters_current"], (p.get("historical_2019") or {}).get("turnout_rate"), (p.get("historical_2023") or {}).get("turnout_rate"), (p.get("projection") or {}).get("low"), (p.get("projection") or {}).get("central"), (p.get("projection") or {}).get("high"), (p.get("projection") or {}).get("expected_voters_central"), QUALITY.get(p["data_quality_status"], p["data_quality_status"])] for p in parishes]}
    warning_text = "Se detectó una variación significativa del registro electoral entre procesos. Esta variación puede responder a cambios administrativos, metodológicos o territoriales y no debe interpretarse automáticamente como una tendencia demográfica."
    registration = {"title": "Registro electoral", "subtitle": "ADVERTENCIA SOBRE EL REGISTRO ELECTORAL", "text": warning_text if data["warnings"] else "Evolución descriptiva del registro electoral.", "headers": ["Proceso / cambio", "Electores / cambio absoluto", "Cambio porcentual"], "formats": [None, "integer", "percent"], "rows": [["2019", r19, None], ["2023", r23, None], ["Actual", total, None], ["2019 → 2023", *change(r19, r23)], ["2023 → actual", *change(r23, total)], ["2019 → actual", *change(r19, total)]]}
    inec = {"title": "Contexto INEC", "subtitle": "CONTEXTO TERRITORIAL · OFICIAL · INEC CPV 2022", "text": "Las variables demográficas se presentan exclusivamente como contexto territorial y no intervienen en la fórmula V1. CNE: electores habilitados. INEC: población censada.", "headers": ["Parroquia", "Población", "Hombres", "Mujeres", "0–14", "15–29", "30–44", "45–64", "65+", "Crecimiento", "Densidad"], "formats": [None, "integer", "integer", "integer", "integer", "integer", "integer", "integer", "integer", "percent", "density"], "font_size": 6.0, "rows": [[p["name"], p["demographics"].get("POP_TOTAL"), p["demographics"].get("POP_MALE"), p["demographics"].get("POP_FEMALE"), p["demographics"].get("AGE_0_14"), p["demographics"].get("AGE_15_29"), p["demographics"].get("AGE_30_44"), p["demographics"].get("AGE_45_64"), p["demographics"].get("AGE_65_PLUS"), p["demographics"].get("POPULATION_GROWTH", p["demographics"].get("POP_GROWTH")), p["demographics"].get("POPULATION_DENSITY", p["demographics"].get("DENSITY"))] for p in parishes]}
    method_text = f"{UNIVERSE}\n\nModelo: {projection['model_code']} · Versión: {projection['model_version']}\nCENTRAL: 35 % × participación 2019 + 65 % × participación 2023. LOW: menor tasa observada entre 2019 y 2023 por parroquia. HIGH: mayor tasa observada entre 2019 y 2023 por parroquia. Votantes esperados: electores actuales × tasa proyectada.\n\n{WARNING}"
    methodology = {"title": "Metodología", "subtitle": "UNIVERSO DE PROYECCIÓN", "text": method_text, "headers": ["Parroquia", "Tasa 2019", "35 % × 2019", "Tasa 2023", "65 % × 2023", "Central", "Electores actuales", "Votantes esperados"], "formats": [None, "percent", "percent", "percent", "percent", "percent", "integer", "integer"], "font_size": 6.8, "rows": [[p["name"], (p.get("historical_2019") or {}).get("turnout_rate"), ((p.get("historical_2019") or {}).get("turnout_rate") or 0) * .35, (p.get("historical_2023") or {}).get("turnout_rate"), ((p.get("historical_2023") or {}).get("turnout_rate") or 0) * .65, (p.get("projection") or {}).get("central"), p["registered_voters_current"], (p.get("projection") or {}).get("expected_voters_central")] for p in parishes]}
    sources = {"title": "Fuentes", "subtitle": "FUENTES OFICIALES", "headers": ["Institución", "Dataset", "Fecha de referencia", "Fecha de publicación", "URL oficial"], "formats": [None, None, "date", "date", None], "rows": [[s["institution"], s["dataset"], s.get("reference_date") or (date(s["reference_year"], 1, 1) if s.get("reference_year") else None), s.get("publication_date"), s.get("official_url") or "No registrada"] for s in context.get("sources", [])]}
    return [summary, historical, scenarios, parish, registration, inec, methodology, sources]
